
namespace IAPM
{
    partial class FrmAMSFournisseur
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmAMSFournisseur));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuFormDockAMSFournisseur = new Bunifu.UI.WinForms.BunifuFormDock();
            this.snackBarAMSFournisseur = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.ktReportPDF = new Kimtoo.Reports.ktReport(this.components);
            this.saveFileDialogPDF = new System.Windows.Forms.SaveFileDialog();
            this.grpBoxGestionFournisseur = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuShapes2 = new Bunifu.UI.WinForms.BunifuShapes();
            this.btnPdf = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.shpLigne2 = new Bunifu.UI.WinForms.BunifuShapes();
            this.btnModif = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnSuppr = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnAjout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuShapes1 = new Bunifu.UI.WinForms.BunifuShapes();
            this.lblTitre = new Bunifu.UI.WinForms.BunifuLabel();
            this.pbSeparateur = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.shwPnlDgv = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.dgvAMSFournisseur = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.grpBoxInfoFournisseur = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.tbIdFournisseur = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbNomFournisseur = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbVilleFournisseur = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbCpFournisseur = new Bunifu.UI.WinForms.BunifuTextBox();
            this.grpBoxGestionFournisseur.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbSeparateur)).BeginInit();
            this.shwPnlDgv.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvAMSFournisseur)).BeginInit();
            this.grpBoxInfoFournisseur.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuFormDockAMSFournisseur
            // 
            this.bunifuFormDockAMSFournisseur.AllowFormDragging = true;
            this.bunifuFormDockAMSFournisseur.AllowFormDropShadow = true;
            this.bunifuFormDockAMSFournisseur.AllowFormResizing = false;
            this.bunifuFormDockAMSFournisseur.AllowHidingBottomRegion = true;
            this.bunifuFormDockAMSFournisseur.AllowOpacityChangesWhileDragging = true;
            this.bunifuFormDockAMSFournisseur.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDockAMSFournisseur.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDockAMSFournisseur.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDockAMSFournisseur.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDockAMSFournisseur.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDockAMSFournisseur.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDockAMSFournisseur.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDockAMSFournisseur.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDockAMSFournisseur.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDockAMSFournisseur.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDockAMSFournisseur.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDockAMSFournisseur.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDockAMSFournisseur.ContainerControl = this;
            this.bunifuFormDockAMSFournisseur.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDockAMSFournisseur.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDockAMSFournisseur.DockingOptions.DockAll = true;
            this.bunifuFormDockAMSFournisseur.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDockAMSFournisseur.DockingOptions.DockBottomRight = true;
            this.bunifuFormDockAMSFournisseur.DockingOptions.DockFullScreen = true;
            this.bunifuFormDockAMSFournisseur.DockingOptions.DockLeft = true;
            this.bunifuFormDockAMSFournisseur.DockingOptions.DockRight = true;
            this.bunifuFormDockAMSFournisseur.DockingOptions.DockTopLeft = true;
            this.bunifuFormDockAMSFournisseur.DockingOptions.DockTopRight = true;
            this.bunifuFormDockAMSFournisseur.FormDraggingOpacity = 0.9D;
            this.bunifuFormDockAMSFournisseur.ParentForm = this;
            this.bunifuFormDockAMSFournisseur.ShowCursorChanges = true;
            this.bunifuFormDockAMSFournisseur.ShowDockingIndicators = true;
            this.bunifuFormDockAMSFournisseur.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDockAMSFournisseur.TitleBarOptions.BunifuFormDock = this.bunifuFormDockAMSFournisseur;
            this.bunifuFormDockAMSFournisseur.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDockAMSFournisseur.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDockAMSFournisseur.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // snackBarAMSFournisseur
            // 
            this.snackBarAMSFournisseur.AllowDragging = false;
            this.snackBarAMSFournisseur.AllowMultipleViews = true;
            this.snackBarAMSFournisseur.ClickToClose = true;
            this.snackBarAMSFournisseur.DoubleClickToClose = true;
            this.snackBarAMSFournisseur.DurationAfterIdle = 3000;
            this.snackBarAMSFournisseur.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSFournisseur.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSFournisseur.ErrorOptions.ActionBorderRadius = 1;
            this.snackBarAMSFournisseur.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackBarAMSFournisseur.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackBarAMSFournisseur.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.snackBarAMSFournisseur.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.snackBarAMSFournisseur.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.snackBarAMSFournisseur.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackBarAMSFournisseur.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.snackBarAMSFournisseur.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.snackBarAMSFournisseur.ErrorOptions.IconLeftMargin = 12;
            this.snackBarAMSFournisseur.FadeCloseIcon = false;
            this.snackBarAMSFournisseur.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.snackBarAMSFournisseur.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSFournisseur.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSFournisseur.InformationOptions.ActionBorderRadius = 1;
            this.snackBarAMSFournisseur.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackBarAMSFournisseur.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackBarAMSFournisseur.InformationOptions.BackColor = System.Drawing.Color.White;
            this.snackBarAMSFournisseur.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.snackBarAMSFournisseur.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.snackBarAMSFournisseur.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackBarAMSFournisseur.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.snackBarAMSFournisseur.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.snackBarAMSFournisseur.InformationOptions.IconLeftMargin = 12;
            this.snackBarAMSFournisseur.Margin = 10;
            this.snackBarAMSFournisseur.MaximumSize = new System.Drawing.Size(0, 0);
            this.snackBarAMSFournisseur.MaximumViews = 7;
            this.snackBarAMSFournisseur.MessageRightMargin = 15;
            this.snackBarAMSFournisseur.MinimumSize = new System.Drawing.Size(0, 0);
            this.snackBarAMSFournisseur.ShowBorders = true;
            this.snackBarAMSFournisseur.ShowCloseIcon = false;
            this.snackBarAMSFournisseur.ShowIcon = true;
            this.snackBarAMSFournisseur.ShowShadows = true;
            this.snackBarAMSFournisseur.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSFournisseur.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSFournisseur.SuccessOptions.ActionBorderRadius = 1;
            this.snackBarAMSFournisseur.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackBarAMSFournisseur.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackBarAMSFournisseur.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.snackBarAMSFournisseur.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.snackBarAMSFournisseur.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.snackBarAMSFournisseur.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackBarAMSFournisseur.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.snackBarAMSFournisseur.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.snackBarAMSFournisseur.SuccessOptions.IconLeftMargin = 12;
            this.snackBarAMSFournisseur.ViewsMargin = 7;
            this.snackBarAMSFournisseur.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSFournisseur.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSFournisseur.WarningOptions.ActionBorderRadius = 1;
            this.snackBarAMSFournisseur.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackBarAMSFournisseur.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackBarAMSFournisseur.WarningOptions.BackColor = System.Drawing.Color.White;
            this.snackBarAMSFournisseur.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.snackBarAMSFournisseur.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.snackBarAMSFournisseur.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackBarAMSFournisseur.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.snackBarAMSFournisseur.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.snackBarAMSFournisseur.WarningOptions.IconLeftMargin = 12;
            this.snackBarAMSFournisseur.ZoomCloseIcon = true;
            // 
            // ktReportPDF
            // 
            this.ktReportPDF.AlternativeRowBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(229)))), ((int)(((byte)(229)))));
            this.ktReportPDF.AlternativeRowGridColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(61)))), ((int)(((byte)(65)))));
            this.ktReportPDF.HeaderBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(183)))), ((int)(((byte)(197)))));
            this.ktReportPDF.HeaderFontColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(46)))));
            this.ktReportPDF.HeaderGridColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(61)))), ((int)(((byte)(65)))));
            this.ktReportPDF.RowDefaultBackgroudColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.ktReportPDF.RowDefaultFontColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(46)))));
            this.ktReportPDF.RowDefaultGridColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(61)))), ((int)(((byte)(65)))));
            // 
            // grpBoxGestionFournisseur
            // 
            this.grpBoxGestionFournisseur.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.grpBoxGestionFournisseur.BorderRadius = 3;
            this.grpBoxGestionFournisseur.BorderThickness = 4;
            this.grpBoxGestionFournisseur.Controls.Add(this.bunifuShapes2);
            this.grpBoxGestionFournisseur.Controls.Add(this.btnPdf);
            this.grpBoxGestionFournisseur.Controls.Add(this.shpLigne2);
            this.grpBoxGestionFournisseur.Controls.Add(this.btnModif);
            this.grpBoxGestionFournisseur.Controls.Add(this.btnSuppr);
            this.grpBoxGestionFournisseur.Controls.Add(this.btnAjout);
            this.grpBoxGestionFournisseur.Controls.Add(this.bunifuShapes1);
            this.grpBoxGestionFournisseur.Font = new System.Drawing.Font("Bahnschrift SemiLight", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grpBoxGestionFournisseur.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.grpBoxGestionFournisseur.LabelIndent = 10;
            this.grpBoxGestionFournisseur.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.grpBoxGestionFournisseur.Location = new System.Drawing.Point(45, 523);
            this.grpBoxGestionFournisseur.Name = "grpBoxGestionFournisseur";
            this.grpBoxGestionFournisseur.Size = new System.Drawing.Size(1128, 99);
            this.grpBoxGestionFournisseur.TabIndex = 44;
            this.grpBoxGestionFournisseur.TabStop = false;
            this.grpBoxGestionFournisseur.Text = "Gestion des fournisseurs";
            // 
            // bunifuShapes2
            // 
            this.bunifuShapes2.Angle = 0F;
            this.bunifuShapes2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShapes2.BorderColor = System.Drawing.Color.Silver;
            this.bunifuShapes2.BorderThickness = 2;
            this.bunifuShapes2.FillColor = System.Drawing.Color.Transparent;
            this.bunifuShapes2.FillShape = true;
            this.bunifuShapes2.Location = new System.Drawing.Point(836, 44);
            this.bunifuShapes2.Name = "bunifuShapes2";
            this.bunifuShapes2.Shape = Bunifu.UI.WinForms.BunifuShapes.Shapes.Line;
            this.bunifuShapes2.Sides = 5;
            this.bunifuShapes2.Size = new System.Drawing.Size(47, 22);
            this.bunifuShapes2.TabIndex = 28;
            this.bunifuShapes2.Text = "shpLigne";
            // 
            // btnPdf
            // 
            this.btnPdf.AllowAnimations = true;
            this.btnPdf.AllowMouseEffects = true;
            this.btnPdf.AllowToggling = false;
            this.btnPdf.AnimationSpeed = 200;
            this.btnPdf.AutoGenerateColors = false;
            this.btnPdf.AutoRoundBorders = false;
            this.btnPdf.AutoSizeLeftIcon = true;
            this.btnPdf.AutoSizeRightIcon = true;
            this.btnPdf.BackColor = System.Drawing.Color.Transparent;
            this.btnPdf.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(203)))), ((int)(((byte)(139)))));
            this.btnPdf.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPdf.BackgroundImage")));
            this.btnPdf.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnPdf.ButtonText = "Générer un PDF";
            this.btnPdf.ButtonTextMarginLeft = 0;
            this.btnPdf.ColorContrastOnClick = 45;
            this.btnPdf.ColorContrastOnHover = 45;
            this.btnPdf.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnPdf.CustomizableEdges = borderEdges1;
            this.btnPdf.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPdf.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPdf.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPdf.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPdf.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnPdf.Font = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPdf.ForeColor = System.Drawing.Color.White;
            this.btnPdf.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPdf.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPdf.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnPdf.IconMarginLeft = 11;
            this.btnPdf.IconPadding = 10;
            this.btnPdf.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPdf.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPdf.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPdf.IconSize = 25;
            this.btnPdf.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(203)))), ((int)(((byte)(139)))));
            this.btnPdf.IdleBorderRadius = 15;
            this.btnPdf.IdleBorderThickness = 1;
            this.btnPdf.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(203)))), ((int)(((byte)(139)))));
            this.btnPdf.IdleIconLeftImage = null;
            this.btnPdf.IdleIconRightImage = null;
            this.btnPdf.IndicateFocus = false;
            this.btnPdf.Location = new System.Drawing.Point(691, 39);
            this.btnPdf.Name = "btnPdf";
            this.btnPdf.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPdf.OnDisabledState.BorderRadius = 15;
            this.btnPdf.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnPdf.OnDisabledState.BorderThickness = 1;
            this.btnPdf.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPdf.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPdf.OnDisabledState.IconLeftImage = null;
            this.btnPdf.OnDisabledState.IconRightImage = null;
            this.btnPdf.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnPdf.onHoverState.BorderRadius = 15;
            this.btnPdf.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnPdf.onHoverState.BorderThickness = 1;
            this.btnPdf.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnPdf.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnPdf.onHoverState.IconLeftImage = null;
            this.btnPdf.onHoverState.IconRightImage = null;
            this.btnPdf.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(203)))), ((int)(((byte)(139)))));
            this.btnPdf.OnIdleState.BorderRadius = 15;
            this.btnPdf.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnPdf.OnIdleState.BorderThickness = 1;
            this.btnPdf.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(203)))), ((int)(((byte)(139)))));
            this.btnPdf.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnPdf.OnIdleState.IconLeftImage = null;
            this.btnPdf.OnIdleState.IconRightImage = null;
            this.btnPdf.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnPdf.OnPressedState.BorderRadius = 15;
            this.btnPdf.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnPdf.OnPressedState.BorderThickness = 1;
            this.btnPdf.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnPdf.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnPdf.OnPressedState.IconLeftImage = null;
            this.btnPdf.OnPressedState.IconRightImage = null;
            this.btnPdf.Size = new System.Drawing.Size(130, 32);
            this.btnPdf.TabIndex = 27;
            this.btnPdf.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPdf.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPdf.TextMarginLeft = 0;
            this.btnPdf.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnPdf.UseDefaultRadiusAndThickness = true;
            this.btnPdf.Click += new System.EventHandler(this.btnPdf_Click);
            // 
            // shpLigne2
            // 
            this.shpLigne2.Angle = 0F;
            this.shpLigne2.BackColor = System.Drawing.Color.Transparent;
            this.shpLigne2.BorderColor = System.Drawing.Color.Silver;
            this.shpLigne2.BorderThickness = 2;
            this.shpLigne2.FillColor = System.Drawing.Color.Transparent;
            this.shpLigne2.FillShape = true;
            this.shpLigne2.Location = new System.Drawing.Point(629, 44);
            this.shpLigne2.Name = "shpLigne2";
            this.shpLigne2.Shape = Bunifu.UI.WinForms.BunifuShapes.Shapes.Line;
            this.shpLigne2.Sides = 5;
            this.shpLigne2.Size = new System.Drawing.Size(47, 22);
            this.shpLigne2.TabIndex = 26;
            this.shpLigne2.Text = "shpLigne";
            // 
            // btnModif
            // 
            this.btnModif.AllowAnimations = true;
            this.btnModif.AllowMouseEffects = true;
            this.btnModif.AllowToggling = false;
            this.btnModif.AnimationSpeed = 200;
            this.btnModif.AutoGenerateColors = false;
            this.btnModif.AutoRoundBorders = false;
            this.btnModif.AutoSizeLeftIcon = true;
            this.btnModif.AutoSizeRightIcon = true;
            this.btnModif.BackColor = System.Drawing.Color.Transparent;
            this.btnModif.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(135)))), ((int)(((byte)(112)))));
            this.btnModif.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnModif.BackgroundImage")));
            this.btnModif.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnModif.ButtonText = "Modifier";
            this.btnModif.ButtonTextMarginLeft = 0;
            this.btnModif.ColorContrastOnClick = 45;
            this.btnModif.ColorContrastOnHover = 45;
            this.btnModif.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnModif.CustomizableEdges = borderEdges2;
            this.btnModif.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnModif.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModif.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModif.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModif.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnModif.Font = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnModif.ForeColor = System.Drawing.Color.White;
            this.btnModif.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnModif.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnModif.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnModif.IconMarginLeft = 11;
            this.btnModif.IconPadding = 10;
            this.btnModif.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnModif.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnModif.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnModif.IconSize = 25;
            this.btnModif.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(135)))), ((int)(((byte)(112)))));
            this.btnModif.IdleBorderRadius = 15;
            this.btnModif.IdleBorderThickness = 1;
            this.btnModif.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(135)))), ((int)(((byte)(112)))));
            this.btnModif.IdleIconLeftImage = null;
            this.btnModif.IdleIconRightImage = null;
            this.btnModif.IndicateFocus = false;
            this.btnModif.Location = new System.Drawing.Point(383, 39);
            this.btnModif.Name = "btnModif";
            this.btnModif.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModif.OnDisabledState.BorderRadius = 15;
            this.btnModif.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnModif.OnDisabledState.BorderThickness = 1;
            this.btnModif.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModif.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModif.OnDisabledState.IconLeftImage = null;
            this.btnModif.OnDisabledState.IconRightImage = null;
            this.btnModif.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnModif.onHoverState.BorderRadius = 15;
            this.btnModif.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnModif.onHoverState.BorderThickness = 1;
            this.btnModif.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnModif.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnModif.onHoverState.IconLeftImage = null;
            this.btnModif.onHoverState.IconRightImage = null;
            this.btnModif.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(135)))), ((int)(((byte)(112)))));
            this.btnModif.OnIdleState.BorderRadius = 15;
            this.btnModif.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnModif.OnIdleState.BorderThickness = 1;
            this.btnModif.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(135)))), ((int)(((byte)(112)))));
            this.btnModif.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnModif.OnIdleState.IconLeftImage = null;
            this.btnModif.OnIdleState.IconRightImage = null;
            this.btnModif.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnModif.OnPressedState.BorderRadius = 15;
            this.btnModif.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnModif.OnPressedState.BorderThickness = 1;
            this.btnModif.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnModif.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnModif.OnPressedState.IconLeftImage = null;
            this.btnModif.OnPressedState.IconRightImage = null;
            this.btnModif.Size = new System.Drawing.Size(108, 32);
            this.btnModif.TabIndex = 25;
            this.btnModif.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnModif.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnModif.TextMarginLeft = 0;
            this.btnModif.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnModif.UseDefaultRadiusAndThickness = true;
            this.btnModif.Click += new System.EventHandler(this.btnModif_Click);
            // 
            // btnSuppr
            // 
            this.btnSuppr.AllowAnimations = true;
            this.btnSuppr.AllowMouseEffects = true;
            this.btnSuppr.AllowToggling = false;
            this.btnSuppr.AnimationSpeed = 200;
            this.btnSuppr.AutoGenerateColors = false;
            this.btnSuppr.AutoRoundBorders = false;
            this.btnSuppr.AutoSizeLeftIcon = true;
            this.btnSuppr.AutoSizeRightIcon = true;
            this.btnSuppr.BackColor = System.Drawing.Color.Transparent;
            this.btnSuppr.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(97)))), ((int)(((byte)(106)))));
            this.btnSuppr.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSuppr.BackgroundImage")));
            this.btnSuppr.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSuppr.ButtonText = "Supprimer";
            this.btnSuppr.ButtonTextMarginLeft = 0;
            this.btnSuppr.ColorContrastOnClick = 45;
            this.btnSuppr.ColorContrastOnHover = 45;
            this.btnSuppr.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnSuppr.CustomizableEdges = borderEdges3;
            this.btnSuppr.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSuppr.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSuppr.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSuppr.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSuppr.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnSuppr.Font = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSuppr.ForeColor = System.Drawing.Color.White;
            this.btnSuppr.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSuppr.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSuppr.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSuppr.IconMarginLeft = 11;
            this.btnSuppr.IconPadding = 10;
            this.btnSuppr.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSuppr.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSuppr.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSuppr.IconSize = 25;
            this.btnSuppr.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(97)))), ((int)(((byte)(106)))));
            this.btnSuppr.IdleBorderRadius = 15;
            this.btnSuppr.IdleBorderThickness = 1;
            this.btnSuppr.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(97)))), ((int)(((byte)(106)))));
            this.btnSuppr.IdleIconLeftImage = null;
            this.btnSuppr.IdleIconRightImage = null;
            this.btnSuppr.IndicateFocus = false;
            this.btnSuppr.Location = new System.Drawing.Point(506, 39);
            this.btnSuppr.Name = "btnSuppr";
            this.btnSuppr.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSuppr.OnDisabledState.BorderRadius = 15;
            this.btnSuppr.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSuppr.OnDisabledState.BorderThickness = 1;
            this.btnSuppr.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSuppr.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSuppr.OnDisabledState.IconLeftImage = null;
            this.btnSuppr.OnDisabledState.IconRightImage = null;
            this.btnSuppr.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnSuppr.onHoverState.BorderRadius = 15;
            this.btnSuppr.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSuppr.onHoverState.BorderThickness = 1;
            this.btnSuppr.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnSuppr.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSuppr.onHoverState.IconLeftImage = null;
            this.btnSuppr.onHoverState.IconRightImage = null;
            this.btnSuppr.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(97)))), ((int)(((byte)(106)))));
            this.btnSuppr.OnIdleState.BorderRadius = 15;
            this.btnSuppr.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSuppr.OnIdleState.BorderThickness = 1;
            this.btnSuppr.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(97)))), ((int)(((byte)(106)))));
            this.btnSuppr.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSuppr.OnIdleState.IconLeftImage = null;
            this.btnSuppr.OnIdleState.IconRightImage = null;
            this.btnSuppr.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnSuppr.OnPressedState.BorderRadius = 15;
            this.btnSuppr.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSuppr.OnPressedState.BorderThickness = 1;
            this.btnSuppr.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnSuppr.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSuppr.OnPressedState.IconLeftImage = null;
            this.btnSuppr.OnPressedState.IconRightImage = null;
            this.btnSuppr.Size = new System.Drawing.Size(108, 32);
            this.btnSuppr.TabIndex = 25;
            this.btnSuppr.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSuppr.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSuppr.TextMarginLeft = 0;
            this.btnSuppr.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSuppr.UseDefaultRadiusAndThickness = true;
            this.btnSuppr.Click += new System.EventHandler(this.btnSuppr_Click);
            // 
            // btnAjout
            // 
            this.btnAjout.AllowAnimations = true;
            this.btnAjout.AllowMouseEffects = true;
            this.btnAjout.AllowToggling = false;
            this.btnAjout.AnimationSpeed = 200;
            this.btnAjout.AutoGenerateColors = false;
            this.btnAjout.AutoRoundBorders = false;
            this.btnAjout.AutoSizeLeftIcon = true;
            this.btnAjout.AutoSizeRightIcon = true;
            this.btnAjout.BackColor = System.Drawing.Color.Transparent;
            this.btnAjout.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.btnAjout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAjout.BackgroundImage")));
            this.btnAjout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAjout.ButtonText = "Ajouter";
            this.btnAjout.ButtonTextMarginLeft = 0;
            this.btnAjout.ColorContrastOnClick = 45;
            this.btnAjout.ColorContrastOnHover = 45;
            this.btnAjout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnAjout.CustomizableEdges = borderEdges4;
            this.btnAjout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAjout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAjout.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAjout.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAjout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnAjout.Font = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAjout.ForeColor = System.Drawing.Color.White;
            this.btnAjout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAjout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAjout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAjout.IconMarginLeft = 11;
            this.btnAjout.IconPadding = 10;
            this.btnAjout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAjout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAjout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAjout.IconSize = 25;
            this.btnAjout.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.btnAjout.IdleBorderRadius = 15;
            this.btnAjout.IdleBorderThickness = 1;
            this.btnAjout.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.btnAjout.IdleIconLeftImage = null;
            this.btnAjout.IdleIconRightImage = null;
            this.btnAjout.IndicateFocus = false;
            this.btnAjout.Location = new System.Drawing.Point(260, 39);
            this.btnAjout.Name = "btnAjout";
            this.btnAjout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAjout.OnDisabledState.BorderRadius = 15;
            this.btnAjout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAjout.OnDisabledState.BorderThickness = 1;
            this.btnAjout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAjout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAjout.OnDisabledState.IconLeftImage = null;
            this.btnAjout.OnDisabledState.IconRightImage = null;
            this.btnAjout.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnAjout.onHoverState.BorderRadius = 15;
            this.btnAjout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAjout.onHoverState.BorderThickness = 1;
            this.btnAjout.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnAjout.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAjout.onHoverState.IconLeftImage = null;
            this.btnAjout.onHoverState.IconRightImage = null;
            this.btnAjout.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.btnAjout.OnIdleState.BorderRadius = 15;
            this.btnAjout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAjout.OnIdleState.BorderThickness = 1;
            this.btnAjout.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.btnAjout.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAjout.OnIdleState.IconLeftImage = null;
            this.btnAjout.OnIdleState.IconRightImage = null;
            this.btnAjout.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnAjout.OnPressedState.BorderRadius = 15;
            this.btnAjout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAjout.OnPressedState.BorderThickness = 1;
            this.btnAjout.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnAjout.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAjout.OnPressedState.IconLeftImage = null;
            this.btnAjout.OnPressedState.IconRightImage = null;
            this.btnAjout.Size = new System.Drawing.Size(108, 32);
            this.btnAjout.TabIndex = 24;
            this.btnAjout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAjout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAjout.TextMarginLeft = 0;
            this.btnAjout.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAjout.UseDefaultRadiusAndThickness = true;
            this.btnAjout.Click += new System.EventHandler(this.btnAjout_Click);
            // 
            // bunifuShapes1
            // 
            this.bunifuShapes1.Angle = 0F;
            this.bunifuShapes1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShapes1.BorderColor = System.Drawing.Color.Silver;
            this.bunifuShapes1.BorderThickness = 2;
            this.bunifuShapes1.FillColor = System.Drawing.Color.Transparent;
            this.bunifuShapes1.FillShape = true;
            this.bunifuShapes1.Location = new System.Drawing.Point(198, 44);
            this.bunifuShapes1.Name = "bunifuShapes1";
            this.bunifuShapes1.Shape = Bunifu.UI.WinForms.BunifuShapes.Shapes.Line;
            this.bunifuShapes1.Sides = 5;
            this.bunifuShapes1.Size = new System.Drawing.Size(47, 22);
            this.bunifuShapes1.TabIndex = 23;
            this.bunifuShapes1.Text = "shpLigne";
            // 
            // lblTitre
            // 
            this.lblTitre.AllowParentOverrides = false;
            this.lblTitre.AutoEllipsis = false;
            this.lblTitre.CursorType = null;
            this.lblTitre.Font = new System.Drawing.Font("Bahnschrift Condensed", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitre.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.lblTitre.Location = new System.Drawing.Point(50, 70);
            this.lblTitre.Name = "lblTitre";
            this.lblTitre.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTitre.Size = new System.Drawing.Size(432, 40);
            this.lblTitre.TabIndex = 46;
            this.lblTitre.Text = "Ajout . Modif . Supression - Fournisseur";
            this.lblTitre.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.lblTitre.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pbSeparateur
            // 
            this.pbSeparateur.AllowFocused = false;
            this.pbSeparateur.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pbSeparateur.AutoSizeHeight = false;
            this.pbSeparateur.BackColor = System.Drawing.Color.Transparent;
            this.pbSeparateur.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.pbSeparateur.BorderRadius = 0;
            this.pbSeparateur.Image = global::IAPM.Properties.Resources.img_separator;
            this.pbSeparateur.IsCircle = false;
            this.pbSeparateur.Location = new System.Drawing.Point(21, 83);
            this.pbSeparateur.Name = "pbSeparateur";
            this.pbSeparateur.Size = new System.Drawing.Size(771, 81);
            this.pbSeparateur.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbSeparateur.TabIndex = 45;
            this.pbSeparateur.TabStop = false;
            this.pbSeparateur.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Custom;
            // 
            // shwPnlDgv
            // 
            this.shwPnlDgv.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.shwPnlDgv.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.shwPnlDgv.BorderRadius = 3;
            this.shwPnlDgv.BorderThickness = 5;
            this.shwPnlDgv.Controls.Add(this.dgvAMSFournisseur);
            this.shwPnlDgv.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.shwPnlDgv.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.shwPnlDgv.Location = new System.Drawing.Point(35, 163);
            this.shwPnlDgv.Name = "shwPnlDgv";
            this.shwPnlDgv.PanelColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.shwPnlDgv.PanelColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.shwPnlDgv.ShadowColor = System.Drawing.Color.DarkGray;
            this.shwPnlDgv.ShadowDept = 2;
            this.shwPnlDgv.ShadowDepth = 5;
            this.shwPnlDgv.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.shwPnlDgv.ShadowTopLeftVisible = false;
            this.shwPnlDgv.Size = new System.Drawing.Size(687, 337);
            this.shwPnlDgv.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.shwPnlDgv.TabIndex = 47;
            // 
            // dgvAMSFournisseur
            // 
            this.dgvAMSFournisseur.AllowCustomTheming = true;
            this.dgvAMSFournisseur.AllowUserToAddRows = false;
            this.dgvAMSFournisseur.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(72)))), ((int)(((byte)(82)))), ((int)(((byte)(101)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.dgvAMSFournisseur.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvAMSFournisseur.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvAMSFournisseur.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(66)))), ((int)(((byte)(82)))));
            this.dgvAMSFournisseur.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvAMSFournisseur.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvAMSFournisseur.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(66)))), ((int)(((byte)(82)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(52)))), ((int)(((byte)(64)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvAMSFournisseur.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvAMSFournisseur.ColumnHeadersHeight = 40;
            this.dgvAMSFournisseur.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(72)))), ((int)(((byte)(82)))), ((int)(((byte)(101)))));
            this.dgvAMSFournisseur.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvAMSFournisseur.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.dgvAMSFournisseur.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(76)))), ((int)(((byte)(94)))));
            this.dgvAMSFournisseur.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.dgvAMSFournisseur.CurrentTheme.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(66)))), ((int)(((byte)(82)))));
            this.dgvAMSFournisseur.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.dgvAMSFournisseur.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(66)))), ((int)(((byte)(82)))));
            this.dgvAMSFournisseur.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvAMSFournisseur.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.dgvAMSFournisseur.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(52)))), ((int)(((byte)(64)))));
            this.dgvAMSFournisseur.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.dgvAMSFournisseur.CurrentTheme.Name = null;
            this.dgvAMSFournisseur.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.dgvAMSFournisseur.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvAMSFournisseur.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.dgvAMSFournisseur.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(76)))), ((int)(((byte)(94)))));
            this.dgvAMSFournisseur.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(76)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvAMSFournisseur.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvAMSFournisseur.EnableHeadersVisualStyles = false;
            this.dgvAMSFournisseur.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.dgvAMSFournisseur.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(66)))), ((int)(((byte)(82)))));
            this.dgvAMSFournisseur.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvAMSFournisseur.HeaderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.dgvAMSFournisseur.Location = new System.Drawing.Point(10, 15);
            this.dgvAMSFournisseur.Name = "dgvAMSFournisseur";
            this.dgvAMSFournisseur.ReadOnly = true;
            this.dgvAMSFournisseur.RowHeadersVisible = false;
            this.dgvAMSFournisseur.RowTemplate.Height = 40;
            this.dgvAMSFournisseur.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.dgvAMSFournisseur.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvAMSFournisseur.ShowCellErrors = false;
            this.dgvAMSFournisseur.ShowEditingIcon = false;
            this.dgvAMSFournisseur.Size = new System.Drawing.Size(667, 317);
            this.dgvAMSFournisseur.TabIndex = 1;
            this.dgvAMSFournisseur.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.ForestGreen;
            this.dgvAMSFournisseur.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvAMSFournisseur_CellClick);
            // 
            // grpBoxInfoFournisseur
            // 
            this.grpBoxInfoFournisseur.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.grpBoxInfoFournisseur.BorderRadius = 3;
            this.grpBoxInfoFournisseur.BorderThickness = 4;
            this.grpBoxInfoFournisseur.Controls.Add(this.tbIdFournisseur);
            this.grpBoxInfoFournisseur.Controls.Add(this.tbNomFournisseur);
            this.grpBoxInfoFournisseur.Controls.Add(this.tbVilleFournisseur);
            this.grpBoxInfoFournisseur.Controls.Add(this.tbCpFournisseur);
            this.grpBoxInfoFournisseur.Font = new System.Drawing.Font("Bahnschrift SemiLight", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grpBoxInfoFournisseur.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.grpBoxInfoFournisseur.LabelIndent = 10;
            this.grpBoxInfoFournisseur.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.grpBoxInfoFournisseur.Location = new System.Drawing.Point(751, 168);
            this.grpBoxInfoFournisseur.Name = "grpBoxInfoFournisseur";
            this.grpBoxInfoFournisseur.Size = new System.Drawing.Size(422, 332);
            this.grpBoxInfoFournisseur.TabIndex = 48;
            this.grpBoxInfoFournisseur.TabStop = false;
            this.grpBoxInfoFournisseur.Text = "Informations fournisseur";
            // 
            // tbIdFournisseur
            // 
            this.tbIdFournisseur.AcceptsReturn = false;
            this.tbIdFournisseur.AcceptsTab = false;
            this.tbIdFournisseur.AnimationSpeed = 200;
            this.tbIdFournisseur.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbIdFournisseur.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbIdFournisseur.AutoSizeHeight = true;
            this.tbIdFournisseur.BackColor = System.Drawing.Color.Transparent;
            this.tbIdFournisseur.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbIdFournisseur.BackgroundImage")));
            this.tbIdFournisseur.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.tbIdFournisseur.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbIdFournisseur.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbIdFournisseur.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.tbIdFournisseur.BorderRadius = 15;
            this.tbIdFournisseur.BorderThickness = 2;
            this.tbIdFournisseur.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbIdFournisseur.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbIdFournisseur.DefaultFont = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbIdFournisseur.DefaultText = "";
            this.tbIdFournisseur.Enabled = false;
            this.tbIdFournisseur.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbIdFournisseur.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbIdFournisseur.HideSelection = true;
            this.tbIdFournisseur.IconLeft = null;
            this.tbIdFournisseur.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbIdFournisseur.IconPadding = 10;
            this.tbIdFournisseur.IconRight = null;
            this.tbIdFournisseur.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbIdFournisseur.Lines = new string[0];
            this.tbIdFournisseur.Location = new System.Drawing.Point(15, 112);
            this.tbIdFournisseur.MaxLength = 32767;
            this.tbIdFournisseur.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbIdFournisseur.Modified = false;
            this.tbIdFournisseur.Multiline = false;
            this.tbIdFournisseur.Name = "tbIdFournisseur";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbIdFournisseur.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbIdFournisseur.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbIdFournisseur.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbIdFournisseur.OnIdleState = stateProperties4;
            this.tbIdFournisseur.Padding = new System.Windows.Forms.Padding(3);
            this.tbIdFournisseur.PasswordChar = '\0';
            this.tbIdFournisseur.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbIdFournisseur.PlaceholderText = "Identifiant";
            this.tbIdFournisseur.ReadOnly = false;
            this.tbIdFournisseur.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbIdFournisseur.SelectedText = "";
            this.tbIdFournisseur.SelectionLength = 0;
            this.tbIdFournisseur.SelectionStart = 0;
            this.tbIdFournisseur.ShortcutsEnabled = true;
            this.tbIdFournisseur.Size = new System.Drawing.Size(193, 50);
            this.tbIdFournisseur.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbIdFournisseur.TabIndex = 33;
            this.tbIdFournisseur.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbIdFournisseur.TextMarginBottom = 0;
            this.tbIdFournisseur.TextMarginLeft = 3;
            this.tbIdFournisseur.TextMarginTop = 1;
            this.tbIdFournisseur.TextPlaceholder = "Identifiant";
            this.tbIdFournisseur.UseSystemPasswordChar = false;
            this.tbIdFournisseur.WordWrap = true;
            // 
            // tbNomFournisseur
            // 
            this.tbNomFournisseur.AcceptsReturn = false;
            this.tbNomFournisseur.AcceptsTab = false;
            this.tbNomFournisseur.AnimationSpeed = 200;
            this.tbNomFournisseur.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbNomFournisseur.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbNomFournisseur.AutoSizeHeight = true;
            this.tbNomFournisseur.BackColor = System.Drawing.Color.Transparent;
            this.tbNomFournisseur.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbNomFournisseur.BackgroundImage")));
            this.tbNomFournisseur.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.tbNomFournisseur.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbNomFournisseur.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbNomFournisseur.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.tbNomFournisseur.BorderRadius = 15;
            this.tbNomFournisseur.BorderThickness = 2;
            this.tbNomFournisseur.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbNomFournisseur.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNomFournisseur.DefaultFont = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbNomFournisseur.DefaultText = "";
            this.tbNomFournisseur.Enabled = false;
            this.tbNomFournisseur.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbNomFournisseur.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbNomFournisseur.HideSelection = true;
            this.tbNomFournisseur.IconLeft = null;
            this.tbNomFournisseur.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNomFournisseur.IconPadding = 10;
            this.tbNomFournisseur.IconRight = null;
            this.tbNomFournisseur.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNomFournisseur.Lines = new string[0];
            this.tbNomFournisseur.Location = new System.Drawing.Point(214, 112);
            this.tbNomFournisseur.MaxLength = 32767;
            this.tbNomFournisseur.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbNomFournisseur.Modified = false;
            this.tbNomFournisseur.Multiline = false;
            this.tbNomFournisseur.Name = "tbNomFournisseur";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNomFournisseur.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbNomFournisseur.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNomFournisseur.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNomFournisseur.OnIdleState = stateProperties8;
            this.tbNomFournisseur.Padding = new System.Windows.Forms.Padding(3);
            this.tbNomFournisseur.PasswordChar = '\0';
            this.tbNomFournisseur.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbNomFournisseur.PlaceholderText = "Raison sociale";
            this.tbNomFournisseur.ReadOnly = false;
            this.tbNomFournisseur.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbNomFournisseur.SelectedText = "";
            this.tbNomFournisseur.SelectionLength = 0;
            this.tbNomFournisseur.SelectionStart = 0;
            this.tbNomFournisseur.ShortcutsEnabled = true;
            this.tbNomFournisseur.Size = new System.Drawing.Size(193, 50);
            this.tbNomFournisseur.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbNomFournisseur.TabIndex = 34;
            this.tbNomFournisseur.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbNomFournisseur.TextMarginBottom = 0;
            this.tbNomFournisseur.TextMarginLeft = 3;
            this.tbNomFournisseur.TextMarginTop = 1;
            this.tbNomFournisseur.TextPlaceholder = "Raison sociale";
            this.tbNomFournisseur.UseSystemPasswordChar = false;
            this.tbNomFournisseur.WordWrap = true;
            // 
            // tbVilleFournisseur
            // 
            this.tbVilleFournisseur.AcceptsReturn = false;
            this.tbVilleFournisseur.AcceptsTab = false;
            this.tbVilleFournisseur.AnimationSpeed = 200;
            this.tbVilleFournisseur.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbVilleFournisseur.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbVilleFournisseur.AutoSizeHeight = true;
            this.tbVilleFournisseur.BackColor = System.Drawing.Color.Transparent;
            this.tbVilleFournisseur.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbVilleFournisseur.BackgroundImage")));
            this.tbVilleFournisseur.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.tbVilleFournisseur.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbVilleFournisseur.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbVilleFournisseur.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.tbVilleFournisseur.BorderRadius = 15;
            this.tbVilleFournisseur.BorderThickness = 2;
            this.tbVilleFournisseur.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbVilleFournisseur.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbVilleFournisseur.DefaultFont = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbVilleFournisseur.DefaultText = "";
            this.tbVilleFournisseur.Enabled = false;
            this.tbVilleFournisseur.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbVilleFournisseur.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbVilleFournisseur.HideSelection = true;
            this.tbVilleFournisseur.IconLeft = null;
            this.tbVilleFournisseur.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbVilleFournisseur.IconPadding = 10;
            this.tbVilleFournisseur.IconRight = null;
            this.tbVilleFournisseur.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbVilleFournisseur.Lines = new string[0];
            this.tbVilleFournisseur.Location = new System.Drawing.Point(15, 170);
            this.tbVilleFournisseur.MaxLength = 32767;
            this.tbVilleFournisseur.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbVilleFournisseur.Modified = false;
            this.tbVilleFournisseur.Multiline = false;
            this.tbVilleFournisseur.Name = "tbVilleFournisseur";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbVilleFournisseur.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbVilleFournisseur.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbVilleFournisseur.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbVilleFournisseur.OnIdleState = stateProperties12;
            this.tbVilleFournisseur.Padding = new System.Windows.Forms.Padding(3);
            this.tbVilleFournisseur.PasswordChar = '\0';
            this.tbVilleFournisseur.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbVilleFournisseur.PlaceholderText = "Ville";
            this.tbVilleFournisseur.ReadOnly = false;
            this.tbVilleFournisseur.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbVilleFournisseur.SelectedText = "";
            this.tbVilleFournisseur.SelectionLength = 0;
            this.tbVilleFournisseur.SelectionStart = 0;
            this.tbVilleFournisseur.ShortcutsEnabled = true;
            this.tbVilleFournisseur.Size = new System.Drawing.Size(193, 50);
            this.tbVilleFournisseur.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbVilleFournisseur.TabIndex = 35;
            this.tbVilleFournisseur.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbVilleFournisseur.TextMarginBottom = 0;
            this.tbVilleFournisseur.TextMarginLeft = 3;
            this.tbVilleFournisseur.TextMarginTop = 1;
            this.tbVilleFournisseur.TextPlaceholder = "Ville";
            this.tbVilleFournisseur.UseSystemPasswordChar = false;
            this.tbVilleFournisseur.WordWrap = true;
            // 
            // tbCpFournisseur
            // 
            this.tbCpFournisseur.AcceptsReturn = false;
            this.tbCpFournisseur.AcceptsTab = false;
            this.tbCpFournisseur.AnimationSpeed = 200;
            this.tbCpFournisseur.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbCpFournisseur.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbCpFournisseur.AutoSizeHeight = true;
            this.tbCpFournisseur.BackColor = System.Drawing.Color.Transparent;
            this.tbCpFournisseur.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbCpFournisseur.BackgroundImage")));
            this.tbCpFournisseur.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.tbCpFournisseur.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbCpFournisseur.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbCpFournisseur.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.tbCpFournisseur.BorderRadius = 15;
            this.tbCpFournisseur.BorderThickness = 2;
            this.tbCpFournisseur.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbCpFournisseur.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbCpFournisseur.DefaultFont = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbCpFournisseur.DefaultText = "";
            this.tbCpFournisseur.Enabled = false;
            this.tbCpFournisseur.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbCpFournisseur.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbCpFournisseur.HideSelection = true;
            this.tbCpFournisseur.IconLeft = null;
            this.tbCpFournisseur.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbCpFournisseur.IconPadding = 10;
            this.tbCpFournisseur.IconRight = null;
            this.tbCpFournisseur.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbCpFournisseur.Lines = new string[0];
            this.tbCpFournisseur.Location = new System.Drawing.Point(214, 170);
            this.tbCpFournisseur.MaxLength = 32767;
            this.tbCpFournisseur.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbCpFournisseur.Modified = false;
            this.tbCpFournisseur.Multiline = false;
            this.tbCpFournisseur.Name = "tbCpFournisseur";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbCpFournisseur.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbCpFournisseur.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbCpFournisseur.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties16.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbCpFournisseur.OnIdleState = stateProperties16;
            this.tbCpFournisseur.Padding = new System.Windows.Forms.Padding(3);
            this.tbCpFournisseur.PasswordChar = '\0';
            this.tbCpFournisseur.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbCpFournisseur.PlaceholderText = "Code postal";
            this.tbCpFournisseur.ReadOnly = false;
            this.tbCpFournisseur.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbCpFournisseur.SelectedText = "";
            this.tbCpFournisseur.SelectionLength = 0;
            this.tbCpFournisseur.SelectionStart = 0;
            this.tbCpFournisseur.ShortcutsEnabled = true;
            this.tbCpFournisseur.Size = new System.Drawing.Size(193, 50);
            this.tbCpFournisseur.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbCpFournisseur.TabIndex = 36;
            this.tbCpFournisseur.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbCpFournisseur.TextMarginBottom = 0;
            this.tbCpFournisseur.TextMarginLeft = 3;
            this.tbCpFournisseur.TextMarginTop = 1;
            this.tbCpFournisseur.TextPlaceholder = "Code postal";
            this.tbCpFournisseur.UseSystemPasswordChar = false;
            this.tbCpFournisseur.WordWrap = true;
            // 
            // FrmAMSFournisseur
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 17F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.ClientSize = new System.Drawing.Size(1222, 657);
            this.Controls.Add(this.grpBoxInfoFournisseur);
            this.Controls.Add(this.shwPnlDgv);
            this.Controls.Add(this.lblTitre);
            this.Controls.Add(this.pbSeparateur);
            this.Controls.Add(this.grpBoxGestionFournisseur);
            this.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.KeyPreview = true;
            this.Name = "FrmAMSFournisseur";
            this.Text = "";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.FrmAMSFournisseur_FormClosed);
            this.Load += new System.EventHandler(this.FrmAMSFournisseur_Load);
            this.Controls.SetChildIndex(this.grpBoxGestionFournisseur, 0);
            this.Controls.SetChildIndex(this.pbSeparateur, 0);
            this.Controls.SetChildIndex(this.lblTitre, 0);
            this.Controls.SetChildIndex(this.shwPnlDgv, 0);
            this.Controls.SetChildIndex(this.grpBoxInfoFournisseur, 0);
            this.grpBoxGestionFournisseur.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbSeparateur)).EndInit();
            this.shwPnlDgv.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvAMSFournisseur)).EndInit();
            this.grpBoxInfoFournisseur.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDockAMSFournisseur;
        private Bunifu.UI.WinForms.BunifuSnackbar snackBarAMSFournisseur;
        private Kimtoo.Reports.ktReport ktReportPDF;
        private System.Windows.Forms.SaveFileDialog saveFileDialogPDF;
        private Bunifu.UI.WinForms.BunifuGroupBox grpBoxGestionFournisseur;
        private Bunifu.UI.WinForms.BunifuShapes bunifuShapes2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnPdf;
        private Bunifu.UI.WinForms.BunifuShapes shpLigne2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnModif;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnSuppr;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnAjout;
        private Bunifu.UI.WinForms.BunifuShapes bunifuShapes1;
        private Bunifu.UI.WinForms.BunifuLabel lblTitre;
        private Bunifu.UI.WinForms.BunifuPictureBox pbSeparateur;
        private Bunifu.UI.WinForms.BunifuShadowPanel shwPnlDgv;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvAMSFournisseur;
        private Bunifu.UI.WinForms.BunifuGroupBox grpBoxInfoFournisseur;
        private Bunifu.UI.WinForms.BunifuTextBox tbIdFournisseur;
        private Bunifu.UI.WinForms.BunifuTextBox tbNomFournisseur;
        private Bunifu.UI.WinForms.BunifuTextBox tbVilleFournisseur;
        private Bunifu.UI.WinForms.BunifuTextBox tbCpFournisseur;
    }
}