namespace IAPM
{
    partial class FrmAMSCommande
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmAMSCommande));
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.lblTitre = new Bunifu.UI.WinForms.BunifuLabel();
            this.pbSeparateur = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.shwPnlDgv = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.dgvAMSCommande = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.grpBoxInfoClient = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.dtPickerCommande = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.drpDownClientCommande = new Bunifu.UI.WinForms.BunifuDropdown();
            this.tbIdCommande = new Bunifu.UI.WinForms.BunifuTextBox();
            this.grpBoxGestionClient = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuShapes2 = new Bunifu.UI.WinForms.BunifuShapes();
            this.btnAjouter = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.shpLigne2 = new Bunifu.UI.WinForms.BunifuShapes();
            this.btnModif = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnSuppr = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnConsulter = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuShapes1 = new Bunifu.UI.WinForms.BunifuShapes();
            this.bunifuFormDockAMSCommande = new Bunifu.UI.WinForms.BunifuFormDock();
            this.snackBarAMSCommande = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.ktReportPDF = new Kimtoo.Reports.ktReport(this.components);
            this.saveFileDialogPDF = new System.Windows.Forms.SaveFileDialog();
            ((System.ComponentModel.ISupportInitialize)(this.pbSeparateur)).BeginInit();
            this.shwPnlDgv.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvAMSCommande)).BeginInit();
            this.grpBoxInfoClient.SuspendLayout();
            this.grpBoxGestionClient.SuspendLayout();
            this.SuspendLayout();
            // 
            // lblTitre
            // 
            this.lblTitre.AllowParentOverrides = false;
            this.lblTitre.AutoEllipsis = false;
            this.lblTitre.CursorType = null;
            this.lblTitre.Font = new System.Drawing.Font("Bahnschrift Condensed", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitre.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.lblTitre.Location = new System.Drawing.Point(50, 70);
            this.lblTitre.Name = "lblTitre";
            this.lblTitre.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTitre.Size = new System.Drawing.Size(425, 40);
            this.lblTitre.TabIndex = 34;
            this.lblTitre.Text = "Ajout . Modif . Supression - Commande";
            this.lblTitre.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.lblTitre.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pbSeparateur
            // 
            this.pbSeparateur.AllowFocused = false;
            this.pbSeparateur.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pbSeparateur.AutoSizeHeight = false;
            this.pbSeparateur.BackColor = System.Drawing.Color.Transparent;
            this.pbSeparateur.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.pbSeparateur.BorderRadius = 0;
            this.pbSeparateur.Image = global::IAPM.Properties.Resources.img_separator;
            this.pbSeparateur.IsCircle = false;
            this.pbSeparateur.Location = new System.Drawing.Point(32, 83);
            this.pbSeparateur.Name = "pbSeparateur";
            this.pbSeparateur.Size = new System.Drawing.Size(771, 81);
            this.pbSeparateur.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbSeparateur.TabIndex = 33;
            this.pbSeparateur.TabStop = false;
            this.pbSeparateur.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Custom;
            // 
            // shwPnlDgv
            // 
            this.shwPnlDgv.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.shwPnlDgv.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.shwPnlDgv.BorderRadius = 3;
            this.shwPnlDgv.BorderThickness = 5;
            this.shwPnlDgv.Controls.Add(this.dgvAMSCommande);
            this.shwPnlDgv.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.shwPnlDgv.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.shwPnlDgv.Location = new System.Drawing.Point(35, 163);
            this.shwPnlDgv.Name = "shwPnlDgv";
            this.shwPnlDgv.PanelColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.shwPnlDgv.PanelColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.shwPnlDgv.ShadowColor = System.Drawing.Color.DarkGray;
            this.shwPnlDgv.ShadowDept = 2;
            this.shwPnlDgv.ShadowDepth = 5;
            this.shwPnlDgv.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.shwPnlDgv.ShadowTopLeftVisible = false;
            this.shwPnlDgv.Size = new System.Drawing.Size(687, 337);
            this.shwPnlDgv.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.shwPnlDgv.TabIndex = 35;
            // 
            // dgvAMSCommande
            // 
            this.dgvAMSCommande.AllowCustomTheming = true;
            this.dgvAMSCommande.AllowUserToAddRows = false;
            this.dgvAMSCommande.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(72)))), ((int)(((byte)(82)))), ((int)(((byte)(101)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.dgvAMSCommande.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvAMSCommande.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvAMSCommande.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(66)))), ((int)(((byte)(82)))));
            this.dgvAMSCommande.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvAMSCommande.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvAMSCommande.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(66)))), ((int)(((byte)(82)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(52)))), ((int)(((byte)(64)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvAMSCommande.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvAMSCommande.ColumnHeadersHeight = 40;
            this.dgvAMSCommande.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(72)))), ((int)(((byte)(82)))), ((int)(((byte)(101)))));
            this.dgvAMSCommande.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvAMSCommande.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.dgvAMSCommande.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(76)))), ((int)(((byte)(94)))));
            this.dgvAMSCommande.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.dgvAMSCommande.CurrentTheme.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(66)))), ((int)(((byte)(82)))));
            this.dgvAMSCommande.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.dgvAMSCommande.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(66)))), ((int)(((byte)(82)))));
            this.dgvAMSCommande.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvAMSCommande.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.dgvAMSCommande.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(52)))), ((int)(((byte)(64)))));
            this.dgvAMSCommande.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.dgvAMSCommande.CurrentTheme.Name = null;
            this.dgvAMSCommande.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.dgvAMSCommande.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvAMSCommande.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.dgvAMSCommande.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(76)))), ((int)(((byte)(94)))));
            this.dgvAMSCommande.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(76)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvAMSCommande.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvAMSCommande.EnableHeadersVisualStyles = false;
            this.dgvAMSCommande.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.dgvAMSCommande.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(66)))), ((int)(((byte)(82)))));
            this.dgvAMSCommande.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvAMSCommande.HeaderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.dgvAMSCommande.Location = new System.Drawing.Point(10, 15);
            this.dgvAMSCommande.Name = "dgvAMSCommande";
            this.dgvAMSCommande.ReadOnly = true;
            this.dgvAMSCommande.RowHeadersVisible = false;
            this.dgvAMSCommande.RowTemplate.Height = 40;
            this.dgvAMSCommande.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.dgvAMSCommande.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvAMSCommande.ShowCellErrors = false;
            this.dgvAMSCommande.ShowEditingIcon = false;
            this.dgvAMSCommande.Size = new System.Drawing.Size(667, 317);
            this.dgvAMSCommande.TabIndex = 1;
            this.dgvAMSCommande.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.ForestGreen;
            this.dgvAMSCommande.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvAMSCommande_CellClick);
            // 
            // grpBoxInfoClient
            // 
            this.grpBoxInfoClient.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.grpBoxInfoClient.BorderRadius = 3;
            this.grpBoxInfoClient.BorderThickness = 4;
            this.grpBoxInfoClient.Controls.Add(this.dtPickerCommande);
            this.grpBoxInfoClient.Controls.Add(this.drpDownClientCommande);
            this.grpBoxInfoClient.Controls.Add(this.tbIdCommande);
            this.grpBoxInfoClient.Font = new System.Drawing.Font("Bahnschrift SemiLight", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grpBoxInfoClient.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.grpBoxInfoClient.LabelIndent = 10;
            this.grpBoxInfoClient.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.grpBoxInfoClient.Location = new System.Drawing.Point(751, 168);
            this.grpBoxInfoClient.Name = "grpBoxInfoClient";
            this.grpBoxInfoClient.Size = new System.Drawing.Size(248, 332);
            this.grpBoxInfoClient.TabIndex = 43;
            this.grpBoxInfoClient.TabStop = false;
            this.grpBoxInfoClient.Text = "Informations commande";
            // 
            // dtPickerCommande
            // 
            this.dtPickerCommande.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.dtPickerCommande.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.dtPickerCommande.BorderRadius = 0;
            this.dtPickerCommande.Color = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.dtPickerCommande.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dtPickerCommande.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtPickerCommande.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.dtPickerCommande.DisplayWeekNumbers = false;
            this.dtPickerCommande.DPHeight = 0;
            this.dtPickerCommande.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dtPickerCommande.Enabled = false;
            this.dtPickerCommande.FillDatePicker = false;
            this.dtPickerCommande.Font = new System.Drawing.Font("Bahnschrift SemiLight", 12F);
            this.dtPickerCommande.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.dtPickerCommande.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtPickerCommande.Icon = ((System.Drawing.Image)(resources.GetObject("dtPickerCommande.Icon")));
            this.dtPickerCommande.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.dtPickerCommande.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtPickerCommande.LeftTextMargin = 5;
            this.dtPickerCommande.Location = new System.Drawing.Point(19, 209);
            this.dtPickerCommande.MinimumSize = new System.Drawing.Size(4, 32);
            this.dtPickerCommande.Name = "dtPickerCommande";
            this.dtPickerCommande.Size = new System.Drawing.Size(206, 32);
            this.dtPickerCommande.TabIndex = 60;
            // 
            // drpDownClientCommande
            // 
            this.drpDownClientCommande.BackColor = System.Drawing.Color.Transparent;
            this.drpDownClientCommande.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.drpDownClientCommande.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.drpDownClientCommande.BorderRadius = 7;
            this.drpDownClientCommande.Color = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.drpDownClientCommande.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.drpDownClientCommande.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.drpDownClientCommande.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.drpDownClientCommande.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.drpDownClientCommande.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.drpDownClientCommande.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.drpDownClientCommande.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.drpDownClientCommande.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thick;
            this.drpDownClientCommande.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.drpDownClientCommande.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.drpDownClientCommande.Enabled = false;
            this.drpDownClientCommande.FillDropDown = true;
            this.drpDownClientCommande.FillIndicator = false;
            this.drpDownClientCommande.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.drpDownClientCommande.Font = new System.Drawing.Font("Bahnschrift SemiLight", 12F);
            this.drpDownClientCommande.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.drpDownClientCommande.FormattingEnabled = true;
            this.drpDownClientCommande.Icon = null;
            this.drpDownClientCommande.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.drpDownClientCommande.IndicatorColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.drpDownClientCommande.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.drpDownClientCommande.IndicatorThickness = 2;
            this.drpDownClientCommande.IsDropdownOpened = false;
            this.drpDownClientCommande.ItemBackColor = System.Drawing.Color.White;
            this.drpDownClientCommande.ItemBorderColor = System.Drawing.Color.White;
            this.drpDownClientCommande.ItemForeColor = System.Drawing.Color.Black;
            this.drpDownClientCommande.ItemHeight = 37;
            this.drpDownClientCommande.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.drpDownClientCommande.ItemHighLightForeColor = System.Drawing.Color.White;
            this.drpDownClientCommande.ItemTopMargin = 3;
            this.drpDownClientCommande.Location = new System.Drawing.Point(19, 157);
            this.drpDownClientCommande.Name = "drpDownClientCommande";
            this.drpDownClientCommande.Size = new System.Drawing.Size(206, 43);
            this.drpDownClientCommande.TabIndex = 59;
            this.drpDownClientCommande.Text = "Client";
            this.drpDownClientCommande.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.drpDownClientCommande.TextLeftMargin = 5;
            // 
            // tbIdCommande
            // 
            this.tbIdCommande.AcceptsReturn = false;
            this.tbIdCommande.AcceptsTab = false;
            this.tbIdCommande.AnimationSpeed = 10;
            this.tbIdCommande.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbIdCommande.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbIdCommande.AutoSizeHeight = true;
            this.tbIdCommande.BackColor = System.Drawing.Color.Transparent;
            this.tbIdCommande.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbIdCommande.BackgroundImage")));
            this.tbIdCommande.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.tbIdCommande.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbIdCommande.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbIdCommande.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.tbIdCommande.BorderRadius = 15;
            this.tbIdCommande.BorderThickness = 2;
            this.tbIdCommande.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbIdCommande.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbIdCommande.DefaultFont = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbIdCommande.DefaultText = "";
            this.tbIdCommande.Enabled = false;
            this.tbIdCommande.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbIdCommande.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbIdCommande.HideSelection = true;
            this.tbIdCommande.IconLeft = null;
            this.tbIdCommande.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbIdCommande.IconPadding = 10;
            this.tbIdCommande.IconRight = null;
            this.tbIdCommande.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbIdCommande.Lines = new string[0];
            this.tbIdCommande.Location = new System.Drawing.Point(19, 100);
            this.tbIdCommande.MaxLength = 32767;
            this.tbIdCommande.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbIdCommande.Modified = false;
            this.tbIdCommande.Multiline = false;
            this.tbIdCommande.Name = "tbIdCommande";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbIdCommande.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbIdCommande.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbIdCommande.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbIdCommande.OnIdleState = stateProperties4;
            this.tbIdCommande.Padding = new System.Windows.Forms.Padding(3);
            this.tbIdCommande.PasswordChar = '\0';
            this.tbIdCommande.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbIdCommande.PlaceholderText = "Identifiant";
            this.tbIdCommande.ReadOnly = false;
            this.tbIdCommande.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbIdCommande.SelectedText = "";
            this.tbIdCommande.SelectionLength = 0;
            this.tbIdCommande.SelectionStart = 0;
            this.tbIdCommande.ShortcutsEnabled = true;
            this.tbIdCommande.Size = new System.Drawing.Size(206, 50);
            this.tbIdCommande.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbIdCommande.TabIndex = 33;
            this.tbIdCommande.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbIdCommande.TextMarginBottom = 0;
            this.tbIdCommande.TextMarginLeft = 3;
            this.tbIdCommande.TextMarginTop = 1;
            this.tbIdCommande.TextPlaceholder = "Identifiant";
            this.tbIdCommande.UseSystemPasswordChar = false;
            this.tbIdCommande.WordWrap = true;
            // 
            // grpBoxGestionClient
            // 
            this.grpBoxGestionClient.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.grpBoxGestionClient.BorderRadius = 3;
            this.grpBoxGestionClient.BorderThickness = 4;
            this.grpBoxGestionClient.Controls.Add(this.bunifuShapes2);
            this.grpBoxGestionClient.Controls.Add(this.btnAjouter);
            this.grpBoxGestionClient.Controls.Add(this.shpLigne2);
            this.grpBoxGestionClient.Controls.Add(this.btnModif);
            this.grpBoxGestionClient.Controls.Add(this.btnSuppr);
            this.grpBoxGestionClient.Controls.Add(this.btnConsulter);
            this.grpBoxGestionClient.Controls.Add(this.bunifuShapes1);
            this.grpBoxGestionClient.Font = new System.Drawing.Font("Bahnschrift SemiLight", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grpBoxGestionClient.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.grpBoxGestionClient.LabelIndent = 10;
            this.grpBoxGestionClient.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.grpBoxGestionClient.Location = new System.Drawing.Point(45, 523);
            this.grpBoxGestionClient.Name = "grpBoxGestionClient";
            this.grpBoxGestionClient.Size = new System.Drawing.Size(951, 99);
            this.grpBoxGestionClient.TabIndex = 44;
            this.grpBoxGestionClient.TabStop = false;
            this.grpBoxGestionClient.Text = "Gestion des commandes";
            // 
            // bunifuShapes2
            // 
            this.bunifuShapes2.Angle = 0F;
            this.bunifuShapes2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShapes2.BorderColor = System.Drawing.Color.Silver;
            this.bunifuShapes2.BorderThickness = 2;
            this.bunifuShapes2.FillColor = System.Drawing.Color.Transparent;
            this.bunifuShapes2.FillShape = true;
            this.bunifuShapes2.Location = new System.Drawing.Point(781, 44);
            this.bunifuShapes2.Name = "bunifuShapes2";
            this.bunifuShapes2.Shape = Bunifu.UI.WinForms.BunifuShapes.Shapes.Line;
            this.bunifuShapes2.Sides = 5;
            this.bunifuShapes2.Size = new System.Drawing.Size(47, 22);
            this.bunifuShapes2.TabIndex = 28;
            this.bunifuShapes2.Text = "shpLigne";
            // 
            // btnAjouter
            // 
            this.btnAjouter.AllowAnimations = true;
            this.btnAjouter.AllowMouseEffects = true;
            this.btnAjouter.AllowToggling = false;
            this.btnAjouter.AnimationSpeed = 200;
            this.btnAjouter.AutoGenerateColors = false;
            this.btnAjouter.AutoRoundBorders = false;
            this.btnAjouter.AutoSizeLeftIcon = true;
            this.btnAjouter.AutoSizeRightIcon = true;
            this.btnAjouter.BackColor = System.Drawing.Color.Transparent;
            this.btnAjouter.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(203)))), ((int)(((byte)(139)))));
            this.btnAjouter.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAjouter.BackgroundImage")));
            this.btnAjouter.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAjouter.ButtonText = "Nouvelle commande";
            this.btnAjouter.ButtonTextMarginLeft = 0;
            this.btnAjouter.ColorContrastOnClick = 45;
            this.btnAjouter.ColorContrastOnHover = 45;
            this.btnAjouter.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnAjouter.CustomizableEdges = borderEdges1;
            this.btnAjouter.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAjouter.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAjouter.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAjouter.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAjouter.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnAjouter.Font = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAjouter.ForeColor = System.Drawing.Color.White;
            this.btnAjouter.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAjouter.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAjouter.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAjouter.IconMarginLeft = 11;
            this.btnAjouter.IconPadding = 10;
            this.btnAjouter.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAjouter.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAjouter.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAjouter.IconSize = 25;
            this.btnAjouter.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(203)))), ((int)(((byte)(139)))));
            this.btnAjouter.IdleBorderRadius = 15;
            this.btnAjouter.IdleBorderThickness = 1;
            this.btnAjouter.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(203)))), ((int)(((byte)(139)))));
            this.btnAjouter.IdleIconLeftImage = null;
            this.btnAjouter.IdleIconRightImage = null;
            this.btnAjouter.IndicateFocus = false;
            this.btnAjouter.Location = new System.Drawing.Point(596, 39);
            this.btnAjouter.Name = "btnAjouter";
            this.btnAjouter.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAjouter.OnDisabledState.BorderRadius = 15;
            this.btnAjouter.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAjouter.OnDisabledState.BorderThickness = 1;
            this.btnAjouter.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAjouter.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAjouter.OnDisabledState.IconLeftImage = null;
            this.btnAjouter.OnDisabledState.IconRightImage = null;
            this.btnAjouter.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnAjouter.onHoverState.BorderRadius = 15;
            this.btnAjouter.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAjouter.onHoverState.BorderThickness = 1;
            this.btnAjouter.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnAjouter.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAjouter.onHoverState.IconLeftImage = null;
            this.btnAjouter.onHoverState.IconRightImage = null;
            this.btnAjouter.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(203)))), ((int)(((byte)(139)))));
            this.btnAjouter.OnIdleState.BorderRadius = 15;
            this.btnAjouter.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAjouter.OnIdleState.BorderThickness = 1;
            this.btnAjouter.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(203)))), ((int)(((byte)(139)))));
            this.btnAjouter.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAjouter.OnIdleState.IconLeftImage = null;
            this.btnAjouter.OnIdleState.IconRightImage = null;
            this.btnAjouter.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnAjouter.OnPressedState.BorderRadius = 15;
            this.btnAjouter.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAjouter.OnPressedState.BorderThickness = 1;
            this.btnAjouter.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnAjouter.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAjouter.OnPressedState.IconLeftImage = null;
            this.btnAjouter.OnPressedState.IconRightImage = null;
            this.btnAjouter.Size = new System.Drawing.Size(170, 32);
            this.btnAjouter.TabIndex = 27;
            this.btnAjouter.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAjouter.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAjouter.TextMarginLeft = 0;
            this.btnAjouter.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAjouter.UseDefaultRadiusAndThickness = true;
            this.btnAjouter.Click += new System.EventHandler(this.btnAjouter_Click);
            // 
            // shpLigne2
            // 
            this.shpLigne2.Angle = 0F;
            this.shpLigne2.BackColor = System.Drawing.Color.Transparent;
            this.shpLigne2.BorderColor = System.Drawing.Color.Silver;
            this.shpLigne2.BorderThickness = 2;
            this.shpLigne2.FillColor = System.Drawing.Color.Transparent;
            this.shpLigne2.FillShape = true;
            this.shpLigne2.Location = new System.Drawing.Point(534, 44);
            this.shpLigne2.Name = "shpLigne2";
            this.shpLigne2.Shape = Bunifu.UI.WinForms.BunifuShapes.Shapes.Line;
            this.shpLigne2.Sides = 5;
            this.shpLigne2.Size = new System.Drawing.Size(47, 22);
            this.shpLigne2.TabIndex = 26;
            this.shpLigne2.Text = "shpLigne";
            // 
            // btnModif
            // 
            this.btnModif.AllowAnimations = true;
            this.btnModif.AllowMouseEffects = true;
            this.btnModif.AllowToggling = false;
            this.btnModif.AnimationSpeed = 200;
            this.btnModif.AutoGenerateColors = false;
            this.btnModif.AutoRoundBorders = false;
            this.btnModif.AutoSizeLeftIcon = true;
            this.btnModif.AutoSizeRightIcon = true;
            this.btnModif.BackColor = System.Drawing.Color.Transparent;
            this.btnModif.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(135)))), ((int)(((byte)(112)))));
            this.btnModif.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnModif.BackgroundImage")));
            this.btnModif.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnModif.ButtonText = "Modifier";
            this.btnModif.ButtonTextMarginLeft = 0;
            this.btnModif.ColorContrastOnClick = 45;
            this.btnModif.ColorContrastOnHover = 45;
            this.btnModif.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnModif.CustomizableEdges = borderEdges2;
            this.btnModif.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnModif.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModif.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModif.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModif.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnModif.Font = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnModif.ForeColor = System.Drawing.Color.White;
            this.btnModif.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnModif.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnModif.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnModif.IconMarginLeft = 11;
            this.btnModif.IconPadding = 10;
            this.btnModif.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnModif.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnModif.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnModif.IconSize = 25;
            this.btnModif.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(135)))), ((int)(((byte)(112)))));
            this.btnModif.IdleBorderRadius = 15;
            this.btnModif.IdleBorderThickness = 1;
            this.btnModif.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(135)))), ((int)(((byte)(112)))));
            this.btnModif.IdleIconLeftImage = null;
            this.btnModif.IdleIconRightImage = null;
            this.btnModif.IndicateFocus = false;
            this.btnModif.Location = new System.Drawing.Point(288, 39);
            this.btnModif.Name = "btnModif";
            this.btnModif.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModif.OnDisabledState.BorderRadius = 15;
            this.btnModif.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnModif.OnDisabledState.BorderThickness = 1;
            this.btnModif.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModif.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModif.OnDisabledState.IconLeftImage = null;
            this.btnModif.OnDisabledState.IconRightImage = null;
            this.btnModif.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnModif.onHoverState.BorderRadius = 15;
            this.btnModif.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnModif.onHoverState.BorderThickness = 1;
            this.btnModif.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnModif.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnModif.onHoverState.IconLeftImage = null;
            this.btnModif.onHoverState.IconRightImage = null;
            this.btnModif.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(135)))), ((int)(((byte)(112)))));
            this.btnModif.OnIdleState.BorderRadius = 15;
            this.btnModif.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnModif.OnIdleState.BorderThickness = 1;
            this.btnModif.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(135)))), ((int)(((byte)(112)))));
            this.btnModif.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnModif.OnIdleState.IconLeftImage = null;
            this.btnModif.OnIdleState.IconRightImage = null;
            this.btnModif.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnModif.OnPressedState.BorderRadius = 15;
            this.btnModif.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnModif.OnPressedState.BorderThickness = 1;
            this.btnModif.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnModif.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnModif.OnPressedState.IconLeftImage = null;
            this.btnModif.OnPressedState.IconRightImage = null;
            this.btnModif.Size = new System.Drawing.Size(108, 32);
            this.btnModif.TabIndex = 25;
            this.btnModif.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnModif.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnModif.TextMarginLeft = 0;
            this.btnModif.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnModif.UseDefaultRadiusAndThickness = true;
            // 
            // btnSuppr
            // 
            this.btnSuppr.AllowAnimations = true;
            this.btnSuppr.AllowMouseEffects = true;
            this.btnSuppr.AllowToggling = false;
            this.btnSuppr.AnimationSpeed = 200;
            this.btnSuppr.AutoGenerateColors = false;
            this.btnSuppr.AutoRoundBorders = false;
            this.btnSuppr.AutoSizeLeftIcon = true;
            this.btnSuppr.AutoSizeRightIcon = true;
            this.btnSuppr.BackColor = System.Drawing.Color.Transparent;
            this.btnSuppr.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(97)))), ((int)(((byte)(106)))));
            this.btnSuppr.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSuppr.BackgroundImage")));
            this.btnSuppr.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSuppr.ButtonText = "Supprimer";
            this.btnSuppr.ButtonTextMarginLeft = 0;
            this.btnSuppr.ColorContrastOnClick = 45;
            this.btnSuppr.ColorContrastOnHover = 45;
            this.btnSuppr.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnSuppr.CustomizableEdges = borderEdges3;
            this.btnSuppr.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSuppr.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSuppr.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSuppr.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSuppr.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnSuppr.Font = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSuppr.ForeColor = System.Drawing.Color.White;
            this.btnSuppr.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSuppr.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSuppr.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSuppr.IconMarginLeft = 11;
            this.btnSuppr.IconPadding = 10;
            this.btnSuppr.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSuppr.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSuppr.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSuppr.IconSize = 25;
            this.btnSuppr.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(97)))), ((int)(((byte)(106)))));
            this.btnSuppr.IdleBorderRadius = 15;
            this.btnSuppr.IdleBorderThickness = 1;
            this.btnSuppr.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(97)))), ((int)(((byte)(106)))));
            this.btnSuppr.IdleIconLeftImage = null;
            this.btnSuppr.IdleIconRightImage = null;
            this.btnSuppr.IndicateFocus = false;
            this.btnSuppr.Location = new System.Drawing.Point(411, 39);
            this.btnSuppr.Name = "btnSuppr";
            this.btnSuppr.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSuppr.OnDisabledState.BorderRadius = 15;
            this.btnSuppr.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSuppr.OnDisabledState.BorderThickness = 1;
            this.btnSuppr.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSuppr.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSuppr.OnDisabledState.IconLeftImage = null;
            this.btnSuppr.OnDisabledState.IconRightImage = null;
            this.btnSuppr.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnSuppr.onHoverState.BorderRadius = 15;
            this.btnSuppr.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSuppr.onHoverState.BorderThickness = 1;
            this.btnSuppr.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnSuppr.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSuppr.onHoverState.IconLeftImage = null;
            this.btnSuppr.onHoverState.IconRightImage = null;
            this.btnSuppr.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(97)))), ((int)(((byte)(106)))));
            this.btnSuppr.OnIdleState.BorderRadius = 15;
            this.btnSuppr.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSuppr.OnIdleState.BorderThickness = 1;
            this.btnSuppr.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(97)))), ((int)(((byte)(106)))));
            this.btnSuppr.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSuppr.OnIdleState.IconLeftImage = null;
            this.btnSuppr.OnIdleState.IconRightImage = null;
            this.btnSuppr.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnSuppr.OnPressedState.BorderRadius = 15;
            this.btnSuppr.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSuppr.OnPressedState.BorderThickness = 1;
            this.btnSuppr.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnSuppr.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSuppr.OnPressedState.IconLeftImage = null;
            this.btnSuppr.OnPressedState.IconRightImage = null;
            this.btnSuppr.Size = new System.Drawing.Size(108, 32);
            this.btnSuppr.TabIndex = 25;
            this.btnSuppr.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSuppr.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSuppr.TextMarginLeft = 0;
            this.btnSuppr.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSuppr.UseDefaultRadiusAndThickness = true;
            this.btnSuppr.Click += new System.EventHandler(this.btnSuppr_Click);
            // 
            // btnConsulter
            // 
            this.btnConsulter.AllowAnimations = true;
            this.btnConsulter.AllowMouseEffects = true;
            this.btnConsulter.AllowToggling = false;
            this.btnConsulter.AnimationSpeed = 200;
            this.btnConsulter.AutoGenerateColors = false;
            this.btnConsulter.AutoRoundBorders = false;
            this.btnConsulter.AutoSizeLeftIcon = true;
            this.btnConsulter.AutoSizeRightIcon = true;
            this.btnConsulter.BackColor = System.Drawing.Color.Transparent;
            this.btnConsulter.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.btnConsulter.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnConsulter.BackgroundImage")));
            this.btnConsulter.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnConsulter.ButtonText = "Consulter";
            this.btnConsulter.ButtonTextMarginLeft = 0;
            this.btnConsulter.ColorContrastOnClick = 45;
            this.btnConsulter.ColorContrastOnHover = 45;
            this.btnConsulter.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnConsulter.CustomizableEdges = borderEdges4;
            this.btnConsulter.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnConsulter.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnConsulter.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnConsulter.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnConsulter.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnConsulter.Font = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnConsulter.ForeColor = System.Drawing.Color.White;
            this.btnConsulter.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnConsulter.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnConsulter.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnConsulter.IconMarginLeft = 11;
            this.btnConsulter.IconPadding = 10;
            this.btnConsulter.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnConsulter.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnConsulter.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnConsulter.IconSize = 25;
            this.btnConsulter.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.btnConsulter.IdleBorderRadius = 15;
            this.btnConsulter.IdleBorderThickness = 1;
            this.btnConsulter.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.btnConsulter.IdleIconLeftImage = null;
            this.btnConsulter.IdleIconRightImage = null;
            this.btnConsulter.IndicateFocus = false;
            this.btnConsulter.Location = new System.Drawing.Point(165, 39);
            this.btnConsulter.Name = "btnConsulter";
            this.btnConsulter.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnConsulter.OnDisabledState.BorderRadius = 15;
            this.btnConsulter.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnConsulter.OnDisabledState.BorderThickness = 1;
            this.btnConsulter.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnConsulter.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnConsulter.OnDisabledState.IconLeftImage = null;
            this.btnConsulter.OnDisabledState.IconRightImage = null;
            this.btnConsulter.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnConsulter.onHoverState.BorderRadius = 15;
            this.btnConsulter.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnConsulter.onHoverState.BorderThickness = 1;
            this.btnConsulter.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnConsulter.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnConsulter.onHoverState.IconLeftImage = null;
            this.btnConsulter.onHoverState.IconRightImage = null;
            this.btnConsulter.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.btnConsulter.OnIdleState.BorderRadius = 15;
            this.btnConsulter.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnConsulter.OnIdleState.BorderThickness = 1;
            this.btnConsulter.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.btnConsulter.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnConsulter.OnIdleState.IconLeftImage = null;
            this.btnConsulter.OnIdleState.IconRightImage = null;
            this.btnConsulter.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnConsulter.OnPressedState.BorderRadius = 15;
            this.btnConsulter.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnConsulter.OnPressedState.BorderThickness = 1;
            this.btnConsulter.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnConsulter.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnConsulter.OnPressedState.IconLeftImage = null;
            this.btnConsulter.OnPressedState.IconRightImage = null;
            this.btnConsulter.Size = new System.Drawing.Size(108, 32);
            this.btnConsulter.TabIndex = 24;
            this.btnConsulter.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnConsulter.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnConsulter.TextMarginLeft = 0;
            this.btnConsulter.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnConsulter.UseDefaultRadiusAndThickness = true;
            this.btnConsulter.Click += new System.EventHandler(this.btnConsulter_Click);
            // 
            // bunifuShapes1
            // 
            this.bunifuShapes1.Angle = 0F;
            this.bunifuShapes1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShapes1.BorderColor = System.Drawing.Color.Silver;
            this.bunifuShapes1.BorderThickness = 2;
            this.bunifuShapes1.FillColor = System.Drawing.Color.Transparent;
            this.bunifuShapes1.FillShape = true;
            this.bunifuShapes1.Location = new System.Drawing.Point(103, 44);
            this.bunifuShapes1.Name = "bunifuShapes1";
            this.bunifuShapes1.Shape = Bunifu.UI.WinForms.BunifuShapes.Shapes.Line;
            this.bunifuShapes1.Sides = 5;
            this.bunifuShapes1.Size = new System.Drawing.Size(47, 22);
            this.bunifuShapes1.TabIndex = 23;
            this.bunifuShapes1.Text = "shpLigne";
            // 
            // bunifuFormDockAMSCommande
            // 
            this.bunifuFormDockAMSCommande.AllowFormDragging = true;
            this.bunifuFormDockAMSCommande.AllowFormDropShadow = true;
            this.bunifuFormDockAMSCommande.AllowFormResizing = false;
            this.bunifuFormDockAMSCommande.AllowHidingBottomRegion = true;
            this.bunifuFormDockAMSCommande.AllowOpacityChangesWhileDragging = true;
            this.bunifuFormDockAMSCommande.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDockAMSCommande.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDockAMSCommande.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDockAMSCommande.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDockAMSCommande.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDockAMSCommande.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDockAMSCommande.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDockAMSCommande.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDockAMSCommande.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDockAMSCommande.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDockAMSCommande.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDockAMSCommande.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDockAMSCommande.ContainerControl = this;
            this.bunifuFormDockAMSCommande.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDockAMSCommande.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDockAMSCommande.DockingOptions.DockAll = true;
            this.bunifuFormDockAMSCommande.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDockAMSCommande.DockingOptions.DockBottomRight = true;
            this.bunifuFormDockAMSCommande.DockingOptions.DockFullScreen = true;
            this.bunifuFormDockAMSCommande.DockingOptions.DockLeft = true;
            this.bunifuFormDockAMSCommande.DockingOptions.DockRight = true;
            this.bunifuFormDockAMSCommande.DockingOptions.DockTopLeft = true;
            this.bunifuFormDockAMSCommande.DockingOptions.DockTopRight = true;
            this.bunifuFormDockAMSCommande.FormDraggingOpacity = 0.9D;
            this.bunifuFormDockAMSCommande.ParentForm = this;
            this.bunifuFormDockAMSCommande.ShowCursorChanges = true;
            this.bunifuFormDockAMSCommande.ShowDockingIndicators = true;
            this.bunifuFormDockAMSCommande.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDockAMSCommande.TitleBarOptions.BunifuFormDock = this.bunifuFormDockAMSCommande;
            this.bunifuFormDockAMSCommande.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDockAMSCommande.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDockAMSCommande.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // snackBarAMSCommande
            // 
            this.snackBarAMSCommande.AllowDragging = false;
            this.snackBarAMSCommande.AllowMultipleViews = true;
            this.snackBarAMSCommande.ClickToClose = true;
            this.snackBarAMSCommande.DoubleClickToClose = true;
            this.snackBarAMSCommande.DurationAfterIdle = 3000;
            this.snackBarAMSCommande.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSCommande.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSCommande.ErrorOptions.ActionBorderRadius = 1;
            this.snackBarAMSCommande.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackBarAMSCommande.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackBarAMSCommande.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.snackBarAMSCommande.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.snackBarAMSCommande.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.snackBarAMSCommande.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackBarAMSCommande.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.snackBarAMSCommande.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.snackBarAMSCommande.ErrorOptions.IconLeftMargin = 12;
            this.snackBarAMSCommande.FadeCloseIcon = false;
            this.snackBarAMSCommande.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.snackBarAMSCommande.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSCommande.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSCommande.InformationOptions.ActionBorderRadius = 1;
            this.snackBarAMSCommande.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackBarAMSCommande.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackBarAMSCommande.InformationOptions.BackColor = System.Drawing.Color.White;
            this.snackBarAMSCommande.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.snackBarAMSCommande.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.snackBarAMSCommande.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackBarAMSCommande.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.snackBarAMSCommande.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.snackBarAMSCommande.InformationOptions.IconLeftMargin = 12;
            this.snackBarAMSCommande.Margin = 10;
            this.snackBarAMSCommande.MaximumSize = new System.Drawing.Size(0, 0);
            this.snackBarAMSCommande.MaximumViews = 7;
            this.snackBarAMSCommande.MessageRightMargin = 15;
            this.snackBarAMSCommande.MinimumSize = new System.Drawing.Size(0, 0);
            this.snackBarAMSCommande.ShowBorders = true;
            this.snackBarAMSCommande.ShowCloseIcon = false;
            this.snackBarAMSCommande.ShowIcon = true;
            this.snackBarAMSCommande.ShowShadows = true;
            this.snackBarAMSCommande.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSCommande.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSCommande.SuccessOptions.ActionBorderRadius = 1;
            this.snackBarAMSCommande.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackBarAMSCommande.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackBarAMSCommande.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.snackBarAMSCommande.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.snackBarAMSCommande.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.snackBarAMSCommande.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackBarAMSCommande.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.snackBarAMSCommande.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.snackBarAMSCommande.SuccessOptions.IconLeftMargin = 12;
            this.snackBarAMSCommande.ViewsMargin = 7;
            this.snackBarAMSCommande.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSCommande.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarAMSCommande.WarningOptions.ActionBorderRadius = 1;
            this.snackBarAMSCommande.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackBarAMSCommande.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackBarAMSCommande.WarningOptions.BackColor = System.Drawing.Color.White;
            this.snackBarAMSCommande.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.snackBarAMSCommande.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.snackBarAMSCommande.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackBarAMSCommande.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.snackBarAMSCommande.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.snackBarAMSCommande.WarningOptions.IconLeftMargin = 12;
            this.snackBarAMSCommande.ZoomCloseIcon = true;
            // 
            // ktReportPDF
            // 
            this.ktReportPDF.AlternativeRowBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(229)))), ((int)(((byte)(229)))));
            this.ktReportPDF.AlternativeRowGridColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(61)))), ((int)(((byte)(65)))));
            this.ktReportPDF.HeaderBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(183)))), ((int)(((byte)(197)))));
            this.ktReportPDF.HeaderFontColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(46)))));
            this.ktReportPDF.HeaderGridColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(61)))), ((int)(((byte)(65)))));
            this.ktReportPDF.RowDefaultBackgroudColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.ktReportPDF.RowDefaultFontColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(46)))));
            this.ktReportPDF.RowDefaultGridColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(61)))), ((int)(((byte)(65)))));
            // 
            // FrmAMSCommande
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 17F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.ClientSize = new System.Drawing.Size(1045, 657);
            this.Controls.Add(this.grpBoxGestionClient);
            this.Controls.Add(this.grpBoxInfoClient);
            this.Controls.Add(this.shwPnlDgv);
            this.Controls.Add(this.lblTitre);
            this.Controls.Add(this.pbSeparateur);
            this.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.Name = "FrmAMSCommande";
            this.Text = "";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.FrmAMSCommande_FormClosed);
            this.Load += new System.EventHandler(this.FrmAMSCommande_Load);
            this.Controls.SetChildIndex(this.pbSeparateur, 0);
            this.Controls.SetChildIndex(this.lblTitre, 0);
            this.Controls.SetChildIndex(this.shwPnlDgv, 0);
            this.Controls.SetChildIndex(this.grpBoxInfoClient, 0);
            this.Controls.SetChildIndex(this.grpBoxGestionClient, 0);
            ((System.ComponentModel.ISupportInitialize)(this.pbSeparateur)).EndInit();
            this.shwPnlDgv.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvAMSCommande)).EndInit();
            this.grpBoxInfoClient.ResumeLayout(false);
            this.grpBoxGestionClient.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel lblTitre;
        private Bunifu.UI.WinForms.BunifuPictureBox pbSeparateur;
        private Bunifu.UI.WinForms.BunifuShadowPanel shwPnlDgv;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvAMSCommande;
        private Bunifu.UI.WinForms.BunifuGroupBox grpBoxInfoClient;
        private Bunifu.UI.WinForms.BunifuTextBox tbIdCommande;
        private Bunifu.UI.WinForms.BunifuGroupBox grpBoxGestionClient;
        private Bunifu.UI.WinForms.BunifuShapes bunifuShapes2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnAjouter;
        private Bunifu.UI.WinForms.BunifuShapes shpLigne2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnModif;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnSuppr;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnConsulter;
        private Bunifu.UI.WinForms.BunifuShapes bunifuShapes1;
        private Bunifu.UI.WinForms.BunifuDropdown drpDownClientCommande;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDockAMSCommande;
        private Bunifu.UI.WinForms.BunifuSnackbar snackBarAMSCommande;
        private Kimtoo.Reports.ktReport ktReportPDF;
        private System.Windows.Forms.SaveFileDialog saveFileDialogPDF;
        private Bunifu.UI.WinForms.BunifuDatePicker dtPickerCommande;
    }
}