namespace IAPM
{
    partial class FrmDetailCommande
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmDetailCommande));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.grpBoxInfoCommande = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.tbDateCommande = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbClientCommande = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbIdCommande = new Bunifu.UI.WinForms.BunifuTextBox();
            this.grpBoxProduit = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.shwPnlDgv = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.dgvAMSProduitCommande = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.grpBoxGestionProduit = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.tbQuantiteProduit = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnModif = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.shpLine = new Bunifu.UI.WinForms.BunifuShapes();
            this.drpDownProduit = new Bunifu.UI.WinForms.BunifuDropdown();
            this.drpDownCategorie = new Bunifu.UI.WinForms.BunifuDropdown();
            this.btnSuppr = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnAjout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.saveFileDialogPDF = new System.Windows.Forms.SaveFileDialog();
            this.ktReportPDF = new Kimtoo.Reports.ktReport(this.components);
            this.snackBarDetailCommande = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuFormDockDetailCommande = new Bunifu.UI.WinForms.BunifuFormDock();
            this.grpBoxInfoCommande.SuspendLayout();
            this.grpBoxProduit.SuspendLayout();
            this.shwPnlDgv.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvAMSProduitCommande)).BeginInit();
            this.grpBoxGestionProduit.SuspendLayout();
            this.SuspendLayout();
            // 
            // grpBoxInfoCommande
            // 
            this.grpBoxInfoCommande.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.grpBoxInfoCommande.BorderRadius = 3;
            this.grpBoxInfoCommande.BorderThickness = 4;
            this.grpBoxInfoCommande.Controls.Add(this.tbDateCommande);
            this.grpBoxInfoCommande.Controls.Add(this.tbClientCommande);
            this.grpBoxInfoCommande.Controls.Add(this.tbIdCommande);
            this.grpBoxInfoCommande.Font = new System.Drawing.Font("Bahnschrift SemiLight", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grpBoxInfoCommande.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.grpBoxInfoCommande.LabelIndent = 10;
            this.grpBoxInfoCommande.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.grpBoxInfoCommande.Location = new System.Drawing.Point(36, 75);
            this.grpBoxInfoCommande.Name = "grpBoxInfoCommande";
            this.grpBoxInfoCommande.Size = new System.Drawing.Size(974, 101);
            this.grpBoxInfoCommande.TabIndex = 44;
            this.grpBoxInfoCommande.TabStop = false;
            this.grpBoxInfoCommande.Text = "Informations commande";
            // 
            // tbDateCommande
            // 
            this.tbDateCommande.AcceptsReturn = false;
            this.tbDateCommande.AcceptsTab = false;
            this.tbDateCommande.AnimationSpeed = 10;
            this.tbDateCommande.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbDateCommande.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbDateCommande.AutoSizeHeight = true;
            this.tbDateCommande.BackColor = System.Drawing.Color.Transparent;
            this.tbDateCommande.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbDateCommande.BackgroundImage")));
            this.tbDateCommande.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.tbDateCommande.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbDateCommande.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbDateCommande.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.tbDateCommande.BorderRadius = 15;
            this.tbDateCommande.BorderThickness = 2;
            this.tbDateCommande.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbDateCommande.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbDateCommande.DefaultFont = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbDateCommande.DefaultText = "";
            this.tbDateCommande.Enabled = false;
            this.tbDateCommande.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbDateCommande.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbDateCommande.HideSelection = true;
            this.tbDateCommande.IconLeft = null;
            this.tbDateCommande.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbDateCommande.IconPadding = 10;
            this.tbDateCommande.IconRight = null;
            this.tbDateCommande.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbDateCommande.Lines = new string[0];
            this.tbDateCommande.Location = new System.Drawing.Point(624, 30);
            this.tbDateCommande.MaxLength = 32767;
            this.tbDateCommande.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbDateCommande.Modified = false;
            this.tbDateCommande.Multiline = false;
            this.tbDateCommande.Name = "tbDateCommande";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbDateCommande.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbDateCommande.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbDateCommande.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbDateCommande.OnIdleState = stateProperties4;
            this.tbDateCommande.Padding = new System.Windows.Forms.Padding(3);
            this.tbDateCommande.PasswordChar = '\0';
            this.tbDateCommande.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbDateCommande.PlaceholderText = "Date";
            this.tbDateCommande.ReadOnly = false;
            this.tbDateCommande.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbDateCommande.SelectedText = "";
            this.tbDateCommande.SelectionLength = 0;
            this.tbDateCommande.SelectionStart = 0;
            this.tbDateCommande.ShortcutsEnabled = true;
            this.tbDateCommande.Size = new System.Drawing.Size(206, 50);
            this.tbDateCommande.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbDateCommande.TabIndex = 62;
            this.tbDateCommande.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbDateCommande.TextMarginBottom = 0;
            this.tbDateCommande.TextMarginLeft = 3;
            this.tbDateCommande.TextMarginTop = 1;
            this.tbDateCommande.TextPlaceholder = "Date";
            this.tbDateCommande.UseSystemPasswordChar = false;
            this.tbDateCommande.WordWrap = true;
            // 
            // tbClientCommande
            // 
            this.tbClientCommande.AcceptsReturn = false;
            this.tbClientCommande.AcceptsTab = false;
            this.tbClientCommande.AnimationSpeed = 10;
            this.tbClientCommande.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbClientCommande.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbClientCommande.AutoSizeHeight = true;
            this.tbClientCommande.BackColor = System.Drawing.Color.Transparent;
            this.tbClientCommande.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbClientCommande.BackgroundImage")));
            this.tbClientCommande.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.tbClientCommande.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbClientCommande.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbClientCommande.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.tbClientCommande.BorderRadius = 15;
            this.tbClientCommande.BorderThickness = 2;
            this.tbClientCommande.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbClientCommande.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbClientCommande.DefaultFont = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbClientCommande.DefaultText = "";
            this.tbClientCommande.Enabled = false;
            this.tbClientCommande.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbClientCommande.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbClientCommande.HideSelection = true;
            this.tbClientCommande.IconLeft = null;
            this.tbClientCommande.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbClientCommande.IconPadding = 10;
            this.tbClientCommande.IconRight = null;
            this.tbClientCommande.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbClientCommande.Lines = new string[0];
            this.tbClientCommande.Location = new System.Drawing.Point(382, 30);
            this.tbClientCommande.MaxLength = 32767;
            this.tbClientCommande.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbClientCommande.Modified = false;
            this.tbClientCommande.Multiline = false;
            this.tbClientCommande.Name = "tbClientCommande";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbClientCommande.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbClientCommande.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbClientCommande.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbClientCommande.OnIdleState = stateProperties8;
            this.tbClientCommande.Padding = new System.Windows.Forms.Padding(3);
            this.tbClientCommande.PasswordChar = '\0';
            this.tbClientCommande.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbClientCommande.PlaceholderText = "Client";
            this.tbClientCommande.ReadOnly = false;
            this.tbClientCommande.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbClientCommande.SelectedText = "";
            this.tbClientCommande.SelectionLength = 0;
            this.tbClientCommande.SelectionStart = 0;
            this.tbClientCommande.ShortcutsEnabled = true;
            this.tbClientCommande.Size = new System.Drawing.Size(206, 50);
            this.tbClientCommande.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbClientCommande.TabIndex = 61;
            this.tbClientCommande.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbClientCommande.TextMarginBottom = 0;
            this.tbClientCommande.TextMarginLeft = 3;
            this.tbClientCommande.TextMarginTop = 1;
            this.tbClientCommande.TextPlaceholder = "Client";
            this.tbClientCommande.UseSystemPasswordChar = false;
            this.tbClientCommande.WordWrap = true;
            // 
            // tbIdCommande
            // 
            this.tbIdCommande.AcceptsReturn = false;
            this.tbIdCommande.AcceptsTab = false;
            this.tbIdCommande.AnimationSpeed = 10;
            this.tbIdCommande.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbIdCommande.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbIdCommande.AutoSizeHeight = true;
            this.tbIdCommande.BackColor = System.Drawing.Color.Transparent;
            this.tbIdCommande.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbIdCommande.BackgroundImage")));
            this.tbIdCommande.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.tbIdCommande.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbIdCommande.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbIdCommande.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.tbIdCommande.BorderRadius = 15;
            this.tbIdCommande.BorderThickness = 2;
            this.tbIdCommande.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbIdCommande.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbIdCommande.DefaultFont = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbIdCommande.DefaultText = "";
            this.tbIdCommande.Enabled = false;
            this.tbIdCommande.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbIdCommande.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbIdCommande.HideSelection = true;
            this.tbIdCommande.IconLeft = null;
            this.tbIdCommande.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbIdCommande.IconPadding = 10;
            this.tbIdCommande.IconRight = null;
            this.tbIdCommande.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbIdCommande.Lines = new string[0];
            this.tbIdCommande.Location = new System.Drawing.Point(140, 30);
            this.tbIdCommande.MaxLength = 32767;
            this.tbIdCommande.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbIdCommande.Modified = false;
            this.tbIdCommande.Multiline = false;
            this.tbIdCommande.Name = "tbIdCommande";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbIdCommande.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbIdCommande.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbIdCommande.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbIdCommande.OnIdleState = stateProperties12;
            this.tbIdCommande.Padding = new System.Windows.Forms.Padding(3);
            this.tbIdCommande.PasswordChar = '\0';
            this.tbIdCommande.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbIdCommande.PlaceholderText = "Identifiant";
            this.tbIdCommande.ReadOnly = false;
            this.tbIdCommande.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbIdCommande.SelectedText = "";
            this.tbIdCommande.SelectionLength = 0;
            this.tbIdCommande.SelectionStart = 0;
            this.tbIdCommande.ShortcutsEnabled = true;
            this.tbIdCommande.Size = new System.Drawing.Size(206, 50);
            this.tbIdCommande.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbIdCommande.TabIndex = 33;
            this.tbIdCommande.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbIdCommande.TextMarginBottom = 0;
            this.tbIdCommande.TextMarginLeft = 3;
            this.tbIdCommande.TextMarginTop = 1;
            this.tbIdCommande.TextPlaceholder = "Identifiant";
            this.tbIdCommande.UseSystemPasswordChar = false;
            this.tbIdCommande.WordWrap = true;
            // 
            // grpBoxProduit
            // 
            this.grpBoxProduit.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.grpBoxProduit.BorderRadius = 3;
            this.grpBoxProduit.BorderThickness = 4;
            this.grpBoxProduit.Controls.Add(this.shwPnlDgv);
            this.grpBoxProduit.Font = new System.Drawing.Font("Bahnschrift SemiLight", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grpBoxProduit.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.grpBoxProduit.LabelIndent = 10;
            this.grpBoxProduit.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.grpBoxProduit.Location = new System.Drawing.Point(36, 197);
            this.grpBoxProduit.Name = "grpBoxProduit";
            this.grpBoxProduit.Size = new System.Drawing.Size(974, 248);
            this.grpBoxProduit.TabIndex = 63;
            this.grpBoxProduit.TabStop = false;
            this.grpBoxProduit.Text = "Produits de la commande";
            // 
            // shwPnlDgv
            // 
            this.shwPnlDgv.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.shwPnlDgv.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.shwPnlDgv.BorderRadius = 3;
            this.shwPnlDgv.BorderThickness = 5;
            this.shwPnlDgv.Controls.Add(this.dgvAMSProduitCommande);
            this.shwPnlDgv.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.shwPnlDgv.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.shwPnlDgv.Location = new System.Drawing.Point(140, 24);
            this.shwPnlDgv.Name = "shwPnlDgv";
            this.shwPnlDgv.PanelColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.shwPnlDgv.PanelColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.shwPnlDgv.ShadowColor = System.Drawing.Color.DarkGray;
            this.shwPnlDgv.ShadowDept = 2;
            this.shwPnlDgv.ShadowDepth = 5;
            this.shwPnlDgv.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.shwPnlDgv.ShadowTopLeftVisible = false;
            this.shwPnlDgv.Size = new System.Drawing.Size(687, 201);
            this.shwPnlDgv.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.shwPnlDgv.TabIndex = 36;
            // 
            // dgvAMSProduitCommande
            // 
            this.dgvAMSProduitCommande.AllowCustomTheming = true;
            this.dgvAMSProduitCommande.AllowUserToAddRows = false;
            this.dgvAMSProduitCommande.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(72)))), ((int)(((byte)(82)))), ((int)(((byte)(101)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.dgvAMSProduitCommande.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvAMSProduitCommande.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvAMSProduitCommande.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(66)))), ((int)(((byte)(82)))));
            this.dgvAMSProduitCommande.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvAMSProduitCommande.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvAMSProduitCommande.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(66)))), ((int)(((byte)(82)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(52)))), ((int)(((byte)(64)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvAMSProduitCommande.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvAMSProduitCommande.ColumnHeadersHeight = 40;
            this.dgvAMSProduitCommande.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(72)))), ((int)(((byte)(82)))), ((int)(((byte)(101)))));
            this.dgvAMSProduitCommande.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvAMSProduitCommande.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.dgvAMSProduitCommande.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(76)))), ((int)(((byte)(94)))));
            this.dgvAMSProduitCommande.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.dgvAMSProduitCommande.CurrentTheme.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(66)))), ((int)(((byte)(82)))));
            this.dgvAMSProduitCommande.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.dgvAMSProduitCommande.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(66)))), ((int)(((byte)(82)))));
            this.dgvAMSProduitCommande.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvAMSProduitCommande.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.dgvAMSProduitCommande.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(52)))), ((int)(((byte)(64)))));
            this.dgvAMSProduitCommande.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.dgvAMSProduitCommande.CurrentTheme.Name = null;
            this.dgvAMSProduitCommande.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.dgvAMSProduitCommande.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvAMSProduitCommande.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.dgvAMSProduitCommande.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(76)))), ((int)(((byte)(94)))));
            this.dgvAMSProduitCommande.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(76)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvAMSProduitCommande.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvAMSProduitCommande.EnableHeadersVisualStyles = false;
            this.dgvAMSProduitCommande.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.dgvAMSProduitCommande.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(66)))), ((int)(((byte)(82)))));
            this.dgvAMSProduitCommande.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvAMSProduitCommande.HeaderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.dgvAMSProduitCommande.Location = new System.Drawing.Point(10, 15);
            this.dgvAMSProduitCommande.Name = "dgvAMSProduitCommande";
            this.dgvAMSProduitCommande.ReadOnly = true;
            this.dgvAMSProduitCommande.RowHeadersVisible = false;
            this.dgvAMSProduitCommande.RowTemplate.Height = 40;
            this.dgvAMSProduitCommande.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.dgvAMSProduitCommande.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvAMSProduitCommande.ShowCellErrors = false;
            this.dgvAMSProduitCommande.ShowEditingIcon = false;
            this.dgvAMSProduitCommande.Size = new System.Drawing.Size(667, 181);
            this.dgvAMSProduitCommande.TabIndex = 1;
            this.dgvAMSProduitCommande.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.ForestGreen;
            this.dgvAMSProduitCommande.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvAMSProduitCommande_CellClick);
            // 
            // grpBoxGestionProduit
            // 
            this.grpBoxGestionProduit.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.grpBoxGestionProduit.BorderRadius = 3;
            this.grpBoxGestionProduit.BorderThickness = 4;
            this.grpBoxGestionProduit.Controls.Add(this.tbQuantiteProduit);
            this.grpBoxGestionProduit.Controls.Add(this.btnModif);
            this.grpBoxGestionProduit.Controls.Add(this.shpLine);
            this.grpBoxGestionProduit.Controls.Add(this.drpDownProduit);
            this.grpBoxGestionProduit.Controls.Add(this.drpDownCategorie);
            this.grpBoxGestionProduit.Controls.Add(this.btnSuppr);
            this.grpBoxGestionProduit.Controls.Add(this.btnAjout);
            this.grpBoxGestionProduit.Font = new System.Drawing.Font("Bahnschrift SemiLight", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grpBoxGestionProduit.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.grpBoxGestionProduit.LabelIndent = 10;
            this.grpBoxGestionProduit.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.grpBoxGestionProduit.Location = new System.Drawing.Point(36, 465);
            this.grpBoxGestionProduit.Name = "grpBoxGestionProduit";
            this.grpBoxGestionProduit.Size = new System.Drawing.Size(974, 136);
            this.grpBoxGestionProduit.TabIndex = 64;
            this.grpBoxGestionProduit.TabStop = false;
            this.grpBoxGestionProduit.Text = "Gestion des produits de la commande";
            // 
            // tbQuantiteProduit
            // 
            this.tbQuantiteProduit.AcceptsReturn = false;
            this.tbQuantiteProduit.AcceptsTab = false;
            this.tbQuantiteProduit.AnimationSpeed = 10;
            this.tbQuantiteProduit.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbQuantiteProduit.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbQuantiteProduit.AutoSizeHeight = true;
            this.tbQuantiteProduit.BackColor = System.Drawing.Color.Transparent;
            this.tbQuantiteProduit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbQuantiteProduit.BackgroundImage")));
            this.tbQuantiteProduit.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.tbQuantiteProduit.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbQuantiteProduit.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbQuantiteProduit.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.tbQuantiteProduit.BorderRadius = 15;
            this.tbQuantiteProduit.BorderThickness = 2;
            this.tbQuantiteProduit.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbQuantiteProduit.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbQuantiteProduit.DefaultFont = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbQuantiteProduit.DefaultText = "";
            this.tbQuantiteProduit.Enabled = false;
            this.tbQuantiteProduit.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.tbQuantiteProduit.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbQuantiteProduit.HideSelection = true;
            this.tbQuantiteProduit.IconLeft = null;
            this.tbQuantiteProduit.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbQuantiteProduit.IconPadding = 10;
            this.tbQuantiteProduit.IconRight = null;
            this.tbQuantiteProduit.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbQuantiteProduit.Lines = new string[0];
            this.tbQuantiteProduit.Location = new System.Drawing.Point(358, 53);
            this.tbQuantiteProduit.MaxLength = 32767;
            this.tbQuantiteProduit.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbQuantiteProduit.Modified = false;
            this.tbQuantiteProduit.Multiline = false;
            this.tbQuantiteProduit.Name = "tbQuantiteProduit";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbQuantiteProduit.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbQuantiteProduit.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbQuantiteProduit.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            stateProperties16.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbQuantiteProduit.OnIdleState = stateProperties16;
            this.tbQuantiteProduit.Padding = new System.Windows.Forms.Padding(3);
            this.tbQuantiteProduit.PasswordChar = '\0';
            this.tbQuantiteProduit.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.tbQuantiteProduit.PlaceholderText = "Quantité";
            this.tbQuantiteProduit.ReadOnly = false;
            this.tbQuantiteProduit.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbQuantiteProduit.SelectedText = "";
            this.tbQuantiteProduit.SelectionLength = 0;
            this.tbQuantiteProduit.SelectionStart = 0;
            this.tbQuantiteProduit.ShortcutsEnabled = true;
            this.tbQuantiteProduit.Size = new System.Drawing.Size(160, 47);
            this.tbQuantiteProduit.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbQuantiteProduit.TabIndex = 63;
            this.tbQuantiteProduit.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbQuantiteProduit.TextMarginBottom = 0;
            this.tbQuantiteProduit.TextMarginLeft = 3;
            this.tbQuantiteProduit.TextMarginTop = 1;
            this.tbQuantiteProduit.TextPlaceholder = "Quantité";
            this.tbQuantiteProduit.UseSystemPasswordChar = false;
            this.tbQuantiteProduit.WordWrap = true;
            // 
            // btnModif
            // 
            this.btnModif.AllowAnimations = true;
            this.btnModif.AllowMouseEffects = true;
            this.btnModif.AllowToggling = false;
            this.btnModif.AnimationSpeed = 200;
            this.btnModif.AutoGenerateColors = false;
            this.btnModif.AutoRoundBorders = false;
            this.btnModif.AutoSizeLeftIcon = true;
            this.btnModif.AutoSizeRightIcon = true;
            this.btnModif.BackColor = System.Drawing.Color.Transparent;
            this.btnModif.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(135)))), ((int)(((byte)(112)))));
            this.btnModif.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnModif.BackgroundImage")));
            this.btnModif.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnModif.ButtonText = "Modifier";
            this.btnModif.ButtonTextMarginLeft = 0;
            this.btnModif.ColorContrastOnClick = 45;
            this.btnModif.ColorContrastOnHover = 45;
            this.btnModif.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnModif.CustomizableEdges = borderEdges1;
            this.btnModif.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnModif.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModif.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModif.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModif.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnModif.Font = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnModif.ForeColor = System.Drawing.Color.White;
            this.btnModif.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnModif.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnModif.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnModif.IconMarginLeft = 11;
            this.btnModif.IconPadding = 10;
            this.btnModif.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnModif.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnModif.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnModif.IconSize = 25;
            this.btnModif.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(135)))), ((int)(((byte)(112)))));
            this.btnModif.IdleBorderRadius = 15;
            this.btnModif.IdleBorderThickness = 1;
            this.btnModif.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(135)))), ((int)(((byte)(112)))));
            this.btnModif.IdleIconLeftImage = null;
            this.btnModif.IdleIconRightImage = null;
            this.btnModif.IndicateFocus = false;
            this.btnModif.Location = new System.Drawing.Point(720, 60);
            this.btnModif.Name = "btnModif";
            this.btnModif.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModif.OnDisabledState.BorderRadius = 15;
            this.btnModif.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnModif.OnDisabledState.BorderThickness = 1;
            this.btnModif.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModif.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModif.OnDisabledState.IconLeftImage = null;
            this.btnModif.OnDisabledState.IconRightImage = null;
            this.btnModif.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnModif.onHoverState.BorderRadius = 15;
            this.btnModif.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnModif.onHoverState.BorderThickness = 1;
            this.btnModif.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnModif.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnModif.onHoverState.IconLeftImage = null;
            this.btnModif.onHoverState.IconRightImage = null;
            this.btnModif.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(135)))), ((int)(((byte)(112)))));
            this.btnModif.OnIdleState.BorderRadius = 15;
            this.btnModif.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnModif.OnIdleState.BorderThickness = 1;
            this.btnModif.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(135)))), ((int)(((byte)(112)))));
            this.btnModif.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnModif.OnIdleState.IconLeftImage = null;
            this.btnModif.OnIdleState.IconRightImage = null;
            this.btnModif.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnModif.OnPressedState.BorderRadius = 15;
            this.btnModif.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnModif.OnPressedState.BorderThickness = 1;
            this.btnModif.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnModif.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnModif.OnPressedState.IconLeftImage = null;
            this.btnModif.OnPressedState.IconRightImage = null;
            this.btnModif.Size = new System.Drawing.Size(108, 32);
            this.btnModif.TabIndex = 63;
            this.btnModif.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnModif.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnModif.TextMarginLeft = 0;
            this.btnModif.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnModif.UseDefaultRadiusAndThickness = true;
            this.btnModif.Click += new System.EventHandler(this.btnModif_Click);
            // 
            // shpLine
            // 
            this.shpLine.Angle = 0F;
            this.shpLine.BackColor = System.Drawing.Color.Transparent;
            this.shpLine.BorderColor = System.Drawing.Color.Silver;
            this.shpLine.BorderThickness = 2;
            this.shpLine.FillColor = System.Drawing.Color.Transparent;
            this.shpLine.FillShape = true;
            this.shpLine.Location = new System.Drawing.Point(532, 53);
            this.shpLine.Name = "shpLine";
            this.shpLine.Shape = Bunifu.UI.WinForms.BunifuShapes.Shapes.Line;
            this.shpLine.Sides = 5;
            this.shpLine.Size = new System.Drawing.Size(60, 47);
            this.shpLine.TabIndex = 62;
            this.shpLine.Text = "shpLigne";
            // 
            // drpDownProduit
            // 
            this.drpDownProduit.BackColor = System.Drawing.Color.Transparent;
            this.drpDownProduit.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.drpDownProduit.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.drpDownProduit.BorderRadius = 7;
            this.drpDownProduit.Color = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.drpDownProduit.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.drpDownProduit.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.drpDownProduit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.drpDownProduit.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.drpDownProduit.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.drpDownProduit.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.drpDownProduit.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.drpDownProduit.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thick;
            this.drpDownProduit.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.drpDownProduit.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.drpDownProduit.Enabled = false;
            this.drpDownProduit.FillDropDown = true;
            this.drpDownProduit.FillIndicator = false;
            this.drpDownProduit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.drpDownProduit.Font = new System.Drawing.Font("Bahnschrift SemiLight", 12F);
            this.drpDownProduit.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.drpDownProduit.FormattingEnabled = true;
            this.drpDownProduit.Icon = null;
            this.drpDownProduit.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.drpDownProduit.IndicatorColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.drpDownProduit.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.drpDownProduit.IndicatorThickness = 2;
            this.drpDownProduit.IsDropdownOpened = false;
            this.drpDownProduit.ItemBackColor = System.Drawing.Color.White;
            this.drpDownProduit.ItemBorderColor = System.Drawing.Color.White;
            this.drpDownProduit.ItemForeColor = System.Drawing.Color.Black;
            this.drpDownProduit.ItemHeight = 37;
            this.drpDownProduit.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.drpDownProduit.ItemHighLightForeColor = System.Drawing.Color.White;
            this.drpDownProduit.ItemTopMargin = 3;
            this.drpDownProduit.Location = new System.Drawing.Point(190, 55);
            this.drpDownProduit.Name = "drpDownProduit";
            this.drpDownProduit.Size = new System.Drawing.Size(160, 43);
            this.drpDownProduit.TabIndex = 61;
            this.drpDownProduit.Text = "Produit";
            this.drpDownProduit.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.drpDownProduit.TextLeftMargin = 5;
            // 
            // drpDownCategorie
            // 
            this.drpDownCategorie.BackColor = System.Drawing.Color.Transparent;
            this.drpDownCategorie.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.drpDownCategorie.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.drpDownCategorie.BorderRadius = 7;
            this.drpDownCategorie.Color = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.drpDownCategorie.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.drpDownCategorie.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.drpDownCategorie.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.drpDownCategorie.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.drpDownCategorie.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.drpDownCategorie.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.drpDownCategorie.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.drpDownCategorie.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thick;
            this.drpDownCategorie.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.drpDownCategorie.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.drpDownCategorie.Enabled = false;
            this.drpDownCategorie.FillDropDown = true;
            this.drpDownCategorie.FillIndicator = false;
            this.drpDownCategorie.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.drpDownCategorie.Font = new System.Drawing.Font("Bahnschrift SemiLight", 12F);
            this.drpDownCategorie.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.drpDownCategorie.FormattingEnabled = true;
            this.drpDownCategorie.Icon = null;
            this.drpDownCategorie.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.drpDownCategorie.IndicatorColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.drpDownCategorie.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.drpDownCategorie.IndicatorThickness = 2;
            this.drpDownCategorie.IsDropdownOpened = false;
            this.drpDownCategorie.ItemBackColor = System.Drawing.Color.White;
            this.drpDownCategorie.ItemBorderColor = System.Drawing.Color.White;
            this.drpDownCategorie.ItemForeColor = System.Drawing.Color.Black;
            this.drpDownCategorie.ItemHeight = 37;
            this.drpDownCategorie.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.drpDownCategorie.ItemHighLightForeColor = System.Drawing.Color.White;
            this.drpDownCategorie.ItemTopMargin = 3;
            this.drpDownCategorie.Location = new System.Drawing.Point(22, 55);
            this.drpDownCategorie.Name = "drpDownCategorie";
            this.drpDownCategorie.Size = new System.Drawing.Size(160, 43);
            this.drpDownCategorie.TabIndex = 60;
            this.drpDownCategorie.Text = "Categorie";
            this.drpDownCategorie.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.drpDownCategorie.TextLeftMargin = 5;
            this.drpDownCategorie.SelectedIndexChanged += new System.EventHandler(this.drpDownCategorie_SelectedIndexChanged);
            // 
            // btnSuppr
            // 
            this.btnSuppr.AllowAnimations = true;
            this.btnSuppr.AllowMouseEffects = true;
            this.btnSuppr.AllowToggling = false;
            this.btnSuppr.AnimationSpeed = 200;
            this.btnSuppr.AutoGenerateColors = false;
            this.btnSuppr.AutoRoundBorders = false;
            this.btnSuppr.AutoSizeLeftIcon = true;
            this.btnSuppr.AutoSizeRightIcon = true;
            this.btnSuppr.BackColor = System.Drawing.Color.Transparent;
            this.btnSuppr.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(97)))), ((int)(((byte)(106)))));
            this.btnSuppr.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSuppr.BackgroundImage")));
            this.btnSuppr.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSuppr.ButtonText = "Supprimer";
            this.btnSuppr.ButtonTextMarginLeft = 0;
            this.btnSuppr.ColorContrastOnClick = 45;
            this.btnSuppr.ColorContrastOnHover = 45;
            this.btnSuppr.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnSuppr.CustomizableEdges = borderEdges2;
            this.btnSuppr.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSuppr.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSuppr.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSuppr.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSuppr.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnSuppr.Font = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSuppr.ForeColor = System.Drawing.Color.White;
            this.btnSuppr.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSuppr.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSuppr.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSuppr.IconMarginLeft = 11;
            this.btnSuppr.IconPadding = 10;
            this.btnSuppr.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSuppr.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSuppr.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSuppr.IconSize = 25;
            this.btnSuppr.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(97)))), ((int)(((byte)(106)))));
            this.btnSuppr.IdleBorderRadius = 15;
            this.btnSuppr.IdleBorderThickness = 1;
            this.btnSuppr.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(97)))), ((int)(((byte)(106)))));
            this.btnSuppr.IdleIconLeftImage = null;
            this.btnSuppr.IdleIconRightImage = null;
            this.btnSuppr.IndicateFocus = false;
            this.btnSuppr.Location = new System.Drawing.Point(838, 60);
            this.btnSuppr.Name = "btnSuppr";
            this.btnSuppr.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSuppr.OnDisabledState.BorderRadius = 15;
            this.btnSuppr.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSuppr.OnDisabledState.BorderThickness = 1;
            this.btnSuppr.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSuppr.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSuppr.OnDisabledState.IconLeftImage = null;
            this.btnSuppr.OnDisabledState.IconRightImage = null;
            this.btnSuppr.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnSuppr.onHoverState.BorderRadius = 15;
            this.btnSuppr.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSuppr.onHoverState.BorderThickness = 1;
            this.btnSuppr.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnSuppr.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSuppr.onHoverState.IconLeftImage = null;
            this.btnSuppr.onHoverState.IconRightImage = null;
            this.btnSuppr.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(97)))), ((int)(((byte)(106)))));
            this.btnSuppr.OnIdleState.BorderRadius = 15;
            this.btnSuppr.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSuppr.OnIdleState.BorderThickness = 1;
            this.btnSuppr.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(97)))), ((int)(((byte)(106)))));
            this.btnSuppr.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSuppr.OnIdleState.IconLeftImage = null;
            this.btnSuppr.OnIdleState.IconRightImage = null;
            this.btnSuppr.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnSuppr.OnPressedState.BorderRadius = 15;
            this.btnSuppr.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSuppr.OnPressedState.BorderThickness = 1;
            this.btnSuppr.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnSuppr.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSuppr.OnPressedState.IconLeftImage = null;
            this.btnSuppr.OnPressedState.IconRightImage = null;
            this.btnSuppr.Size = new System.Drawing.Size(108, 32);
            this.btnSuppr.TabIndex = 25;
            this.btnSuppr.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSuppr.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSuppr.TextMarginLeft = 0;
            this.btnSuppr.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSuppr.UseDefaultRadiusAndThickness = true;
            this.btnSuppr.Click += new System.EventHandler(this.btnSuppr_Click);
            // 
            // btnAjout
            // 
            this.btnAjout.AllowAnimations = true;
            this.btnAjout.AllowMouseEffects = true;
            this.btnAjout.AllowToggling = false;
            this.btnAjout.AnimationSpeed = 200;
            this.btnAjout.AutoGenerateColors = false;
            this.btnAjout.AutoRoundBorders = false;
            this.btnAjout.AutoSizeLeftIcon = true;
            this.btnAjout.AutoSizeRightIcon = true;
            this.btnAjout.BackColor = System.Drawing.Color.Transparent;
            this.btnAjout.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.btnAjout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAjout.BackgroundImage")));
            this.btnAjout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAjout.ButtonText = "Ajouter";
            this.btnAjout.ButtonTextMarginLeft = 0;
            this.btnAjout.ColorContrastOnClick = 45;
            this.btnAjout.ColorContrastOnHover = 45;
            this.btnAjout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnAjout.CustomizableEdges = borderEdges3;
            this.btnAjout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAjout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAjout.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAjout.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAjout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnAjout.Font = new System.Drawing.Font("Bahnschrift SemiLight", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAjout.ForeColor = System.Drawing.Color.White;
            this.btnAjout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAjout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAjout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAjout.IconMarginLeft = 11;
            this.btnAjout.IconPadding = 10;
            this.btnAjout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAjout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAjout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAjout.IconSize = 25;
            this.btnAjout.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.btnAjout.IdleBorderRadius = 15;
            this.btnAjout.IdleBorderThickness = 1;
            this.btnAjout.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.btnAjout.IdleIconLeftImage = null;
            this.btnAjout.IdleIconRightImage = null;
            this.btnAjout.IndicateFocus = false;
            this.btnAjout.Location = new System.Drawing.Point(602, 60);
            this.btnAjout.Name = "btnAjout";
            this.btnAjout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAjout.OnDisabledState.BorderRadius = 15;
            this.btnAjout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAjout.OnDisabledState.BorderThickness = 1;
            this.btnAjout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAjout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAjout.OnDisabledState.IconLeftImage = null;
            this.btnAjout.OnDisabledState.IconRightImage = null;
            this.btnAjout.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnAjout.onHoverState.BorderRadius = 15;
            this.btnAjout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAjout.onHoverState.BorderThickness = 1;
            this.btnAjout.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(163)))), ((int)(((byte)(190)))), ((int)(((byte)(140)))));
            this.btnAjout.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAjout.onHoverState.IconLeftImage = null;
            this.btnAjout.onHoverState.IconRightImage = null;
            this.btnAjout.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.btnAjout.OnIdleState.BorderRadius = 15;
            this.btnAjout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAjout.OnIdleState.BorderThickness = 1;
            this.btnAjout.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(129)))), ((int)(((byte)(161)))), ((int)(((byte)(193)))));
            this.btnAjout.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAjout.OnIdleState.IconLeftImage = null;
            this.btnAjout.OnIdleState.IconRightImage = null;
            this.btnAjout.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnAjout.OnPressedState.BorderRadius = 15;
            this.btnAjout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAjout.OnPressedState.BorderThickness = 1;
            this.btnAjout.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(142)))), ((int)(((byte)(173)))));
            this.btnAjout.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAjout.OnPressedState.IconLeftImage = null;
            this.btnAjout.OnPressedState.IconRightImage = null;
            this.btnAjout.Size = new System.Drawing.Size(108, 32);
            this.btnAjout.TabIndex = 24;
            this.btnAjout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAjout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAjout.TextMarginLeft = 0;
            this.btnAjout.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAjout.UseDefaultRadiusAndThickness = true;
            this.btnAjout.Click += new System.EventHandler(this.btnAjout_Click);
            // 
            // ktReportPDF
            // 
            this.ktReportPDF.AlternativeRowBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(229)))), ((int)(((byte)(229)))));
            this.ktReportPDF.AlternativeRowGridColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(61)))), ((int)(((byte)(65)))));
            this.ktReportPDF.HeaderBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(183)))), ((int)(((byte)(197)))));
            this.ktReportPDF.HeaderFontColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(46)))));
            this.ktReportPDF.HeaderGridColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(61)))), ((int)(((byte)(65)))));
            this.ktReportPDF.RowDefaultBackgroudColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.ktReportPDF.RowDefaultFontColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(46)))));
            this.ktReportPDF.RowDefaultGridColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(61)))), ((int)(((byte)(65)))));
            // 
            // snackBarDetailCommande
            // 
            this.snackBarDetailCommande.AllowDragging = false;
            this.snackBarDetailCommande.AllowMultipleViews = true;
            this.snackBarDetailCommande.ClickToClose = true;
            this.snackBarDetailCommande.DoubleClickToClose = true;
            this.snackBarDetailCommande.DurationAfterIdle = 3000;
            this.snackBarDetailCommande.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarDetailCommande.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarDetailCommande.ErrorOptions.ActionBorderRadius = 1;
            this.snackBarDetailCommande.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackBarDetailCommande.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackBarDetailCommande.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.snackBarDetailCommande.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.snackBarDetailCommande.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.snackBarDetailCommande.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackBarDetailCommande.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.snackBarDetailCommande.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.snackBarDetailCommande.ErrorOptions.IconLeftMargin = 12;
            this.snackBarDetailCommande.FadeCloseIcon = false;
            this.snackBarDetailCommande.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.snackBarDetailCommande.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarDetailCommande.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarDetailCommande.InformationOptions.ActionBorderRadius = 1;
            this.snackBarDetailCommande.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackBarDetailCommande.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackBarDetailCommande.InformationOptions.BackColor = System.Drawing.Color.White;
            this.snackBarDetailCommande.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.snackBarDetailCommande.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.snackBarDetailCommande.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackBarDetailCommande.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.snackBarDetailCommande.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.snackBarDetailCommande.InformationOptions.IconLeftMargin = 12;
            this.snackBarDetailCommande.Margin = 10;
            this.snackBarDetailCommande.MaximumSize = new System.Drawing.Size(0, 0);
            this.snackBarDetailCommande.MaximumViews = 7;
            this.snackBarDetailCommande.MessageRightMargin = 15;
            this.snackBarDetailCommande.MinimumSize = new System.Drawing.Size(0, 0);
            this.snackBarDetailCommande.ShowBorders = true;
            this.snackBarDetailCommande.ShowCloseIcon = false;
            this.snackBarDetailCommande.ShowIcon = true;
            this.snackBarDetailCommande.ShowShadows = true;
            this.snackBarDetailCommande.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarDetailCommande.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarDetailCommande.SuccessOptions.ActionBorderRadius = 1;
            this.snackBarDetailCommande.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackBarDetailCommande.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackBarDetailCommande.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.snackBarDetailCommande.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.snackBarDetailCommande.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.snackBarDetailCommande.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackBarDetailCommande.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.snackBarDetailCommande.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.snackBarDetailCommande.SuccessOptions.IconLeftMargin = 12;
            this.snackBarDetailCommande.ViewsMargin = 7;
            this.snackBarDetailCommande.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarDetailCommande.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackBarDetailCommande.WarningOptions.ActionBorderRadius = 1;
            this.snackBarDetailCommande.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackBarDetailCommande.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackBarDetailCommande.WarningOptions.BackColor = System.Drawing.Color.White;
            this.snackBarDetailCommande.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.snackBarDetailCommande.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.snackBarDetailCommande.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackBarDetailCommande.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.snackBarDetailCommande.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.snackBarDetailCommande.WarningOptions.IconLeftMargin = 12;
            this.snackBarDetailCommande.ZoomCloseIcon = true;
            // 
            // bunifuFormDockDetailCommande
            // 
            this.bunifuFormDockDetailCommande.AllowFormDragging = true;
            this.bunifuFormDockDetailCommande.AllowFormDropShadow = true;
            this.bunifuFormDockDetailCommande.AllowFormResizing = false;
            this.bunifuFormDockDetailCommande.AllowHidingBottomRegion = true;
            this.bunifuFormDockDetailCommande.AllowOpacityChangesWhileDragging = true;
            this.bunifuFormDockDetailCommande.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDockDetailCommande.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDockDetailCommande.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDockDetailCommande.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDockDetailCommande.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDockDetailCommande.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDockDetailCommande.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDockDetailCommande.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDockDetailCommande.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDockDetailCommande.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDockDetailCommande.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDockDetailCommande.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDockDetailCommande.ContainerControl = this;
            this.bunifuFormDockDetailCommande.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDockDetailCommande.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDockDetailCommande.DockingOptions.DockAll = true;
            this.bunifuFormDockDetailCommande.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDockDetailCommande.DockingOptions.DockBottomRight = true;
            this.bunifuFormDockDetailCommande.DockingOptions.DockFullScreen = true;
            this.bunifuFormDockDetailCommande.DockingOptions.DockLeft = true;
            this.bunifuFormDockDetailCommande.DockingOptions.DockRight = true;
            this.bunifuFormDockDetailCommande.DockingOptions.DockTopLeft = true;
            this.bunifuFormDockDetailCommande.DockingOptions.DockTopRight = true;
            this.bunifuFormDockDetailCommande.FormDraggingOpacity = 0.9D;
            this.bunifuFormDockDetailCommande.ParentForm = this;
            this.bunifuFormDockDetailCommande.ShowCursorChanges = true;
            this.bunifuFormDockDetailCommande.ShowDockingIndicators = true;
            this.bunifuFormDockDetailCommande.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDockDetailCommande.TitleBarOptions.BunifuFormDock = this.bunifuFormDockDetailCommande;
            this.bunifuFormDockDetailCommande.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDockDetailCommande.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDockDetailCommande.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // FrmDetailCommande
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 17F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(244)))));
            this.ClientSize = new System.Drawing.Size(1045, 657);
            this.Controls.Add(this.grpBoxGestionProduit);
            this.Controls.Add(this.grpBoxProduit);
            this.Controls.Add(this.grpBoxInfoCommande);
            this.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(86)))), ((int)(((byte)(106)))));
            this.KeyPreview = true;
            this.Name = "FrmDetailCommande";
            this.Text = "";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.FrmDetailCommande_FormClosed);
            this.Load += new System.EventHandler(this.FrmDetailCommande_Load);
            this.KeyDown += new System.Windows.Forms.KeyEventHandler(this.FrmDetailCommande_KeyDown);
            this.Controls.SetChildIndex(this.grpBoxInfoCommande, 0);
            this.Controls.SetChildIndex(this.grpBoxProduit, 0);
            this.Controls.SetChildIndex(this.grpBoxGestionProduit, 0);
            this.grpBoxInfoCommande.ResumeLayout(false);
            this.grpBoxProduit.ResumeLayout(false);
            this.shwPnlDgv.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvAMSProduitCommande)).EndInit();
            this.grpBoxGestionProduit.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGroupBox grpBoxInfoCommande;
        private Bunifu.UI.WinForms.BunifuTextBox tbIdCommande;
        private Bunifu.UI.WinForms.BunifuTextBox tbClientCommande;
        private Bunifu.UI.WinForms.BunifuTextBox tbDateCommande;
        private Bunifu.UI.WinForms.BunifuGroupBox grpBoxProduit;
        private Bunifu.UI.WinForms.BunifuShadowPanel shwPnlDgv;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvAMSProduitCommande;
        private Bunifu.UI.WinForms.BunifuGroupBox grpBoxGestionProduit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnSuppr;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnAjout;
        private Bunifu.UI.WinForms.BunifuDropdown drpDownProduit;
        private Bunifu.UI.WinForms.BunifuDropdown drpDownCategorie;
        private Bunifu.UI.WinForms.BunifuShapes shpLine;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnModif;
        private System.Windows.Forms.SaveFileDialog saveFileDialogPDF;
        private Kimtoo.Reports.ktReport ktReportPDF;
        private Bunifu.UI.WinForms.BunifuSnackbar snackBarDetailCommande;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDockDetailCommande;
        private Bunifu.UI.WinForms.BunifuTextBox tbQuantiteProduit;
    }
}